### ISSUE TITLE
Debugger Performance Issues

### ISSUE THREAD

**Issue by jpd002** [jpd002/Play-#1019]
So, I've been trying to debug quite a lot lately and I noticed that it was super slow to launch the emulator and step through the code while using a Debug build. 

I've pinpointed the issue to size hints being requested to the data model for a lot of rows every time the views are refreshed. Seems there's an alternate way of specifying the hints, as demonstrated here: https://github.com/jpd002/Play-/commit/03ed8b2cf5b4c48dfc114b5ae11d110bdb558654. This results in a very nice performance improvement, but obviously needs some tweaking because it breaks some stuff.

@Zer0xFF: What are your thoughts about that? Does it makes sense to do this?

**Comment by Zer0xFF** [comment]
this seems reasonable, though you're obviously bypassing Qt default size hinting, which probably calculate the size on the per character bases, which as we see is slow, but should be more accurate, though ill say few pixel lost/gained are probably worth the performance gain.

also, the hint isn't working with auto is because you're multiplying the entire results by 2, you probably wanted something like this `(m_model->CharsPerUnit() + 2) * m_cwidth;` instead

**Comment by jpd002** [comment]
Gotcha 😃 Thanks for the formulae, gonna try that to see if it gives the proper result.

**Comment by jpd002** [comment]
After some struggling, I found a formulae that seems to work with multiple font sizes and on Windows and macOS.

Changes are here: https://github.com/jpd002/Play-/tree/debugger_improvements

Probably going to merge them soon.

**Comment by Zer0xFF** [comment]
this looks good to me 👍

**Comment by jpd002** [comment]
Thanks for having a look!
