### ISSUE TITLE
Android: Navigation

### ISSUE THREAD

**Issue by Thunder07** [jpd002/Play-#104]
is there much point being able to navigate beyond the /sdcard and into root directory?

**Comment by SeannyM** [comment]
Navigating outside of the SD card directory allows for access to external storage.

**Comment by Thunder07** [comment]
Though my phone has no external sd card, I recall samsung devices have something like /sdcard/ext_sd (or something similar)
so even with access to nothing beyond /sdcard you still have access to both storages.

**Comment by Evolution0** [comment]
Some tablets have full usb ports or support via the micro usb port. Restricting access to /sdcard would prevent users from accessing storage connected that way.

**Comment by Thunder07** [comment]
in that case, "is there much point being able to navigate beyond the */storage* and into root directory?"

**Comment by LoungeKatt** [comment]
https://github.com/AbandonedCart/Play-/commit/3b5bb6108b3f01c7b68cc5bb9522c25243626781
^ This didn't make it into the weekly build because there were questions about storing a path, but the gist is that it searches the sdcard and, if it exists, external sdcard. It returns all files that fit the requirements and then choosing one will store the directory it was in to speed up a future search.

**Comment by jpd002** [comment]
Yeah, navigation is kinda bothersome at the moment. @LoungeKatt's solution is pretty good but like he said, I need to look more deeply into his changes.

**Comment by LinkofHyrule89** [comment]
In the future you could optionally restrict it not to go up any further as long as it can get just outside of internal storage where it lists all the USB drives it would be useful since going to root could be confusing to some users. I do really like the whole idea of just displaying all the roms instead of having to navigate to each folder they are kept in.

**Comment by itsmachotime6** [comment]
@LoungeKatt This won't make it because it's immature. I don't care who started it either.

**Comment by itsmachotime9** [comment]
@LinkofHyrule89 It's immature. I don't care who started it.

**Comment by Thunder07** [comment]
Irrelevant now
