### ISSUE TITLE
How to compile for the Web platform?

### ISSUE THREAD

**Issue by rocheston** [jpd002/Play-#1174]
Please provide us instructions for compiling to the web? Emscripten?

**Comment by Stryxus** [comment]
What makes you assume this will ever support WebAssembly or is even compatible with it in the slightest?
This is a very strange request.

**Comment by BypassGoGuardianPLS** [comment]
Stryxus may be an idiot. The first paragraph in the description of play is 

"Play! is a PlayStation2 emulator for Windows, macOS, UNIX, Android, iOS & web browser platforms."

Look at the last three words, and you'll find it works on web platforms.

So, will someone with actual knowledge please let us know how to build Play! on a website.

**Comment by Zer0xFF** [comment]
No need for insults.

If you want to use the web version, you can just go to https://playjs.purei.org/ , this is kept to date with each update to master
Anyone that wants to build this can look at the CI, which is a step by step instruction on how it's done https://github.com/jpd002/Play-/blob/master/.github/workflows/build-js.yaml
If you dont have the knowledge to read the CI config, you shouldn't be worrying about building it, especially as WASM is still a hit and miss, and different versions of WASM will fail due to lack of features etc etc, even current version itself is a hit and miss and will fail to load alot of the loadable games.

**Comment by rocheston** [comment]
Thank you BypassGoGuardianPLS.

**Comment by rocheston** [comment]
Your response shows arrogance. What is wrong with you man?

**Comment by Stryxus** [comment]
People always assuming stuff and having their heads far too forward... It wasnt an insult, it was a geniune point.
WASM support is going to take A LOT of time, that is not here and now or even near.
So hence, a very strange request. A request which isnt possible atm.
