### ISSUE TITLE
Play! doesn't work on 32-bit Windows XP

### ISSUE THREAD

**Issue by Xiaomita** [jpd002/Play-#12]
That error message shows no matter what. I have the right runtimes as noted on the site, libraries, etc. I downloaded the latest build from your site for Windows. No matter what, it says it's not a valid Win32 application. How do you get it working correctly?

**Comment by Xiaomita** [comment]
I will add that the only version I got running is the 2011 one -- any newer ones will not work on XP, at least from my testing.

**Comment by vgturtle127** [comment]
What do you mean "the 2011 one"?

**Comment by Xiaomita** [comment]
The 32-bit one here: http://purei.org/downloads.php

**Comment by jpd002** [comment]
I've made the necessary changes to support WinXP. It should work in the next weekly.

**Comment by Xiaomita** [comment]
@jpd002 Awesome! Great to know.

**Comment by vgturtle127** [comment]
@Xiaomita OK, sorry I was just making sure. lol

@jpd002 Nice work, dude! What version of VS are you using?

**Comment by Xiaomita** [comment]
The latest weekly build for WinXP doesn't work on XP. Instead of saying it's not a valid application, now this:

![capp](https://cloud.githubusercontent.com/assets/8483347/6889136/dd86be2c-d65d-11e4-9f56-2f6fa9673de5.jpg)

Right after clicking on it, a few seconds passes by and it says the program encountered an error and needs to close. It leaves a log of the crash in "temp" but it's very long and unspecific, and points to no clear reason.

**Comment by jpd002** [comment]
Thanks for testing this new version. The problem might be related to OpenGL, because I did have problems with that when I tested on a WinXP virtual machine, but just thought it was because the video drivers for the virtual machine were crappy.

Let me build a version with OpenGL stuff removed to see if that's really the problem on your side. I'll come back to you soon.

**Comment by jpd002** [comment]
Could you try this to see if you can get the emulator to start under XP?
http://purei.org/downloads/play/temp/Play-0.30-32-NullGS.exe

If the emulator starts with this version, I'll investigate further on the OpenGL side.

**Comment by jpd002** [comment]
@vgturtle127 I'm using Visual Studio 2013.

**Comment by Xiaomita** [comment]
@jpd002 It DOES start, but no game shows anything. I don't know if that's on purpose or not.

**Comment by jpd002** [comment]
Thanks for testing this version. Yes, I've disabled video output on purpose to see if the problem was coming from the OpenGL GS handler. Now that I know that, I'll be able to investigate further.

Could you give me information about your graphics card (card model) and video drivers (nVidia or AMD drivers version)? It will help me figuring out the problem.

**Comment by Xiaomita** [comment]
Well it came with an old, integrated GPU, which is the Intel GMA X4500HD. I think it can handle OpenGL 2 and Direct X11. Do you think the issue is with my graphics driver and hardware? What is Play! try to do when it loads newer builds that has to do with graphics that it didn't do before? If I recall, the 2011 build uses D3D9 or something of that sort, doesn't it? Maybe the problem is due to the OpenGL work. 

Is Play! only OpenGL targeted now and DX backend has deprecated or something?

**Comment by jpd002** [comment]
The 2011 build also uses OpenGL, but it didn't use framebuffer objects as the current build does. I'll have to investigate a bit more to see if I need to use different functions to manage framebuffer objects to stay compatible with older drivers.

**Comment by vgturtle127** [comment]
@jpd002 And you're using the community edition, right? Just making sure. That has better support for XP because of extensions and what not. But since the problem seems to be with graphics API's or @Xiaomita's hardware, I would just say if you are using the regular edition try the Community version and see if it helps.

@Xiaomita If you are running integrated graphics, this will cause problems with many emulators. They also rarely have good support for any graphics API's, and they are critically underpowered. For instance, when my current desktop was still being built, I didn't have a graphics card installed. Most emulators wouldn't even boot, and the ones that did either had error messages or crashed a lot.

However, crashing at launch is a peculiar thing. If this is some bug, it would be the first time I have ever seen anything like it. Although, I would suspect based on experience that the issue is most likely with either your drivers (drivers have been an issue with emulators and integrated graphics in the past), Windows (XP doesn't get updates anymore, which I suppose could cause a problem), or, of course, Play. And if the bug is in Play, then I'm going to go on a limb and say it probably has to do with OpenGL in some way. OpenGL is way harder to manage than people think! I really don't like it. But everything except Windows and the Xbox use it, so I have to get use to it I suppose. :cry:

**Comment by Xiaomita** [comment]
@vgturtle127 You make a good point but I have to disagree with you on the integrated graphics bit. While they are underpowered and that's right that they lack the capabilities of truly dedicated GPUs, the integrated graphics I have (GMA X4500HD) seems to work just fine with PCSX2 and Direct X10. Sure, lots of games are not playable too well with the limited graphics processing power and limited shaders, but I could get games like FFX and FFXII running fullspeed using the D3D9 and D3D10 plugins for PCSX2, so I will go on a limb and say that the issue is probably OpenGL related, yeah; however, I had figured OpenGL issues would occur AFTER the program started when, say, trying to launch a game when the OpenGL context and everything would be setup, but Play! just seems to ... not show anything at all. So if emulators like PCSX2 and Dolphin are good enough for some games, and the integrated chip supports OpenGL 2 and Direct X10, I am going to have to say that it and most newer integrated graphics are probably not as big of an issue as some people make them seem. Maybe the problem is that Play! uses OpenGL > 2?

**Comment by TheLastRar** [comment]
@Xiaomita Integrated chips tend to fair allot worse when faced with OpenGL. if you tried to run PCSX2 using OpenGL mode it will probable fail.

**Comment by Xiaomita** [comment]
@TheLastRar PCSX2's OpenGL backend on Windows seem to increase the performance on some games for me rather than DirectX (with integrated graphics). For example, Final Fantasy 12 goes like 50 FPS on the specs I listed, but with OpenGL and the right settings it can go over 60. So I doubt OpenGL has anything to do with it. The GPU is not very good but it's good enough for PCSX2's OpenGL backend so as long as Play! is OpenGL 2 or lower it should work on my same GPU, all things perfectly.

**Comment by TheLastRar** [comment]
@Xiaomita On my i5-2430M (HD 3000), PCSX2 fails to create an OpenGL 3.3 context, stating that the max supported OpenGL is 3.1.

FiRE.elf on play also crashes when running Play! on integrated graphics. I have to configure Optimus to run on the discrete GPU before Play! can run it.

Granted Play will still load and allow me to attempt emulation, so that issue is different from what has already been mentioned.

**Comment by Xiaomita** [comment]
@TheLastRar I am using older PCSX2 versions that used legacy OpenGL 2 plugins. And as stated before, it can't be that it's integrated graphics because on the same computer with the 2011 version of Play!, I can run games that were supported back then just fine with the same X4500HD chip, and Jean mentions that the only change noted was framebuffer objects in OpenGL. Unless something else changed that I'm unaware of (e.g. OpenGL > 2), I really don't know why Play! isn't working for you unless newer versions use much newer OpenGL.

**Comment by TheLastRar** [comment]
@Xiaomita That would explain why PCSX2 works. As for the issue with Play! I'm just taking guesses and repeating what I've experienced.

**Comment by vgturtle127** [comment]
You have to also take into consideration that some people are good at DirectX but suck at OpenGL (or vice versa). I wouldn't know, I suck at both equally. :smiley: 

Too bad switching to Vulkan and DX12 won't solve all of our problems. If only...

**Comment by Xiaomita** [comment]
I'll just close this issue since the problem is not working on Windows XP but working with my GPU's OpenGL.
