### ISSUE TITLE
Add ppc64le architecture support

### ISSUE THREAD

**Issue by anengineer1** [jpd002/Play-#1250]
ppc64le architecture is one of the few that works with completely open source software an it is growing in popularity during these years.

**Comment by jpd002** [comment]
Closing because it is a duplicate of https://github.com/jpd002/Play-/issues/1222.

As mentioned in that issue, while it would be totally possible to add ppc64le support to the emulator, it's a huge task and again, I don't have any hardware to develop on it. If you'd like to work on that, we can always chat on Discord or something if you need help.

**Comment by anengineer1** [comment]
Thank you a lot, I do know someone with the hardware, I hope to talk about this in the near future with some reinforcements I know, cheers and tank you ;-)

**Comment by anengineer1** [comment]
I completely forgot I wrote that in the past! so sorry
