### ISSUE TITLE
Play! v0.61 changelog where ? 

### ISSUE THREAD

**Issue by spotanjo3** [jpd002/Play-#1260]
Where is the changelog ?

**Comment by jpd002** [comment]
I didn't provide a detail of updates from v0.56 to v0.61 since there is a lot (almost 9 months worth of work). But since you're on GitHub, you can check the diff here: https://github.com/jpd002/Play-/compare/0.56...0.61.

The summary is: Namco System 246 support, some optimizations, some compatibility fixes (some off the top of my head: Devil May Cry screen size fix, some VU spiky polygon fixes, especially in Shinobi, fixes for some odd disappearing textures in Kingdom Hearts on OpenGL, improved video decoding quality, fixed eye rendering on Level 5 games on Vulkan).
