### ISSUE TITLE
Does this program work only on Windows right now?

### ISSUE THREAD

**Issue by frictionmotion** [jpd002/Play-#15]
I have to say that I am a bit confused. Looking at this whole project and the code generator/utilities ones as well, it seems to have a lot of directories and configurations for OS X, Android and iOS. Could anyone clarify what that means? Does this work only on Windows, or are there only compiled Windows binaries to test so far? Does that mean that the Mac/Android/iOS versions are going to be compiled soon or something and Windows is not the only platform this is compatible for? This project seems to have multi-OS/platform portability stuff too.

I see the Android stuff seems to be for testing and it uses data from the main project, no? Does that mean that the other versions are all built off of the Windows one and/or share the same resources to run games?

I'm not really very good at computer programming, especially something crazy complex like this project.

I'd appreciate it if someone could clear some of this up and explain all the other stuff for other OSes.

**Comment by jpd002** [comment]
In a nutshell:
- Only the Windows port works as we speak.
- The OS X port needs to be updated, but should be available again soon.
- The Android port is a work in progress. The emulator compiles, but nothing can run in it yet: the code generator is still missing some important parts and no work has been done on the GS handler.
- There wont be an iOS port of the emulator because of the impossibility of creating executable pages without rooting the device. The iOS parts are only there for the PsfPlayer tool which works because all the code is recompiled in a static object file that is linked with the rest by ld.

I hope that clarifies the reasons for having all those platform folders in there.

**Comment by frictionmotion** [comment]
What do you mean executable pages? You mean executable space protection? What would that be used for and how does iOS/etc. prevent what needs to be done? As far as I remember, emulator developers would often complain that iOS, non-jailbroken, would not be suitable for higher-demand emulators due to the inability of using dynamic binary translation schemes without jailbreaking -- dynarecs/dynamic recompilers; however, latest versions of iOS now allow dynamic linkage, which prior versions did not, regardless of being jailbroken or not. That in itself is a major benefit for GS/GL plugins to render video output.

**Comment by archshift** [comment]
Dynamic linkage is not what's necessary, memory needs to be able to be remapped as executable (which is not possible without jailbreaking) for a dynamic recompiler. Regardless, Apple does not allow emulators in their app store so the user would need to jailbreak anyway.

**Comment by frictionmotion** [comment]
I never said dynamic linkage was necessary; just that it's better for dynamic plugins now. But you are right; it needs to be jailbroken for any real benefit. But also, this apparently never stopped every other working emulator on iOS, so I guess the real showstopper would be the fact that testing it would be a pain without a jailbroken device, among a few other aspects. Other than that, it seems perfectly possible.

**Comment by jpd002** [comment]
I've learned yesterday that it's now possible to execute dynamically generated code on iOS, only if you're running your app in Xcode's debugger. The vm_protect function doesn't fail anymore when specifying VM_PROT_EXECUTE while running on a device. If you run your app without the debugger, the app crashes after running for a few seconds when it tries to run dynamically generated code. 

So, I guess the development of an iOS port of the emulator wouldn't be too difficult, but distribution would still be a pain.

**Comment by LasagnaPie** [comment]
So the focus is on slow, small handheld touchscreen platforms for people to squint at there phones playing PS2 games at 5fps, Be realistic, no handheld device is capable of emulating the PlayStation 2, target a realistic platform, like x86.

**Comment by Embrendassy** [comment]
@LasagnaPie Tiny device is "vague". x86 comes in super-small devices, and ARM can come in giant-sized ones. Form factor != what it's capable of overall. Microsoft's Surface Pro series are a line of tablets, and they are considered handhelds, you could say. We know that newest ones come with i5s/i7s and can certainly handle a degree of PS2/GC/Wii games perfectly as well. The NVIDIA Shield Tegra K1 (ARM device) is already playing Luigi's Mansion full speed, and lots of other games can get half way there or so. I highly doubt a well-optimized PS2 emulator for something in the realm of the that will run games at 5 FPS, since optimization is key, and the debate that PS2 is "harder" than GameCube to emulate has been put to death. They are both hard to emulate, and neither one is necessarily harder than the other/needs more power/resources in general, depending on games of course. It seems to make that, from your negativity towards ARM devices, you just hate the idea of portability and expansion of emulators on architectures other than x86.

**Comment by jpd002** [comment]
Just to be clear, there's no iOS port under development. I was just speculating on the possibility of doing so (I must admit that it would be quite fun to try though).

This project aims to make the emulator as portable as possible, but most of the development done right now is for the Win32 platform.

**Comment by Alegend45** [comment]
What about Linux?

**Comment by jpd002** [comment]
I'm not very familiar with the Linux ecosystem, but I wouldn't be against a Linux port. If anyone's interested working on that, just drop me a line so that we can coordinate our efforts.

**Comment by ProfessorKaos64** [comment]
I'd love this on Linux as well

**Comment by donaldpipowitch** [comment]
The new NVIDIA Shield console seems to be a good candidate for Play. ;)

**Comment by jpd002** [comment]
I've made the changes necessary in CodeGen and Play! to make the OSX port work again. If anyone needs help with the setup, don't hesitate to ask me.

**Comment by jpd002** [comment]
Weekly OSX builds are now available: http://purei.org/downloads/play/weekly/

The UI is not very good, but emulation should be on par with the Windows version.

**Comment by vgturtle127** [comment]
If you have it on Android and OS X, Linux is fairly straightforward. When I get my development machine up and running, I will look into it. :smiley: 

But to answer the original question: No. :laughing:

**Comment by jpd002** [comment]
Closing this issue as original question was answered.
