### ISSUE TITLE
Budokai 1 crashes Play!

### ISSUE THREAD

**Issue by MoochMcGee** [jpd002/Play-#22]
It crashes in CMipsExecutor::PartitionFunction() at line 319.

**Comment by MoochMcGee** [comment]
Apparently, the this pointer points to invalid memory.

**Comment by jpd002** [comment]
Crash was caused by stack corruption when interrupt handler was called on IOP. 3ae11dc849a17a5f55bbade7ee11b19328b2f303 fixes the issue.

The game works now, but it's kinda screwed up probably due to timing issues and the emulator triggering vblanks too often.

![dbzbk1_01](https://cloud.githubusercontent.com/assets/6760433/7060861/e7522f26-de56-11e4-8da7-d944429bd008.jpg)
![dbzbk1_02](https://cloud.githubusercontent.com/assets/6760433/7060862/e8d5e61c-de56-11e4-8443-9678bdf65691.jpg)

**Comment by MoochMcGee** [comment]
It doesn't crash anymore, but for me, I'm just getting a black screen.

**Comment by jpd002** [comment]
Are you using SLUS20591?

**Comment by MoochMcGee** [comment]
Yes.
