### ISSUE TITLE
Romancing SaGa (SLPM_659.20) missing controllers

### ISSUE THREAD

**Issue by exhalatio** [jpd002/Play-#28]
Hi guy!
Romancing SaGa: Minstrel Song SLPM_659.20
Dual shock 2 Controller is not detected.
![saga](https://cloud.githubusercontent.com/assets/7089513/6766932/f02f8d98-d05d-11e4-95b6-7780c1f0ff97.png)

**Comment by jpd002** [comment]
Interesting! What happens if you press the circle button as the message tells you?

**Comment by exhalatio** [comment]
Well, nothing to respond by press the circle button and another buttons.

**Comment by jpd002** [comment]
I've tested the game and I could reproduce the issue. I'll try to see what's wrong as soon as possible.

**Comment by 716Girl** [comment]
This also happens in Arcana Heart in story mode and other game, but I don't remember which one.

**Comment by Xiaomita** [comment]
@jpd002 Didn't you mention an issue with the IOP in other games? The IOP (input-output processor) has problems somehow and that could be the culprit with Romancing SaGa and other games because input is not mapped correctly or something for the game to read/respond?

**Comment by jpd002** [comment]
Issue seems to come from EE syscall SetVSyncFlag not being implemented properly in the emulator. I was able to get the game to go further by hacking the syscall:

![rs_01](https://cloud.githubusercontent.com/assets/6760433/7626654/a1a1d8c4-f9da-11e4-95ce-84344730e43d.jpg)
![rs_02](https://cloud.githubusercontent.com/assets/6760433/7626655/a1a5605c-f9da-11e4-8184-5ac0ffb31082.jpg)
![rs_03](https://cloud.githubusercontent.com/assets/6760433/7626653/a19e9b46-f9da-11e4-84cd-38f999916fb2.jpg)

I still need to figure out what that syscall is supposed to do because the hack breaks other games.

**Comment by jpd002** [comment]
Still working on a proper fix for this, but the last change I made looks promising. Still need to do some more tests.

You can check out the changes for Romancing Saga here: https://github.com/jpd002/Play-/tree/romancing_saga

**Comment by exhalatio** [comment]
@jpd002 Good job. I tested save to memory card, Play! is create the BISLPM-65920-C000 folder but failed to save.
![quicksave](https://cloud.githubusercontent.com/assets/7089513/7746486/a8236ee2-ffed-11e4-9166-a63ea9d7d6df.jpg)

**Comment by jpd002** [comment]
Fixed in 99db9e0d1a2473b56b94c8bd84cbc8980fdb0305. Will be in next weekly build.

**Comment by exhalatio** [comment]
OK, I close it.
