### ISSUE TITLE
Android TV menu system

### ISSUE THREAD

**Issue by AbandonedCart** [jpd002/Play-#301]
I am posting this as an issue since there are a bunch of pull requests that are focused on improving the theme, list, and other things that are slowly making the app incompatible with an Android TV. 

This is being placed here to demonstrate how a shared view is still possible, as the current proposals of an index and other luxury features would make separating the activities an obscenely excessive amount of code to duplicate or convert to shared classes.

https://github.com/AbandonedCart/Play-/commit/085132d8c51830c8a1c4c6ce1bee6ccf40c8a903

**Comment by LoungeKatt** [comment]
And this will restore the toolbar / ActionBar:

https://github.com/AbandonedCart/Play-/commit/814d9e3984786db5a5cae4990b164af0cf189ee4

**Comment by Thunder07** [comment]
I don't have Android TV to test this... but it seems to me you're doing all of this, so that you'd have the drawer open all the time right?

if that's the case, you can avoid most of this and recreating the nav drawer, by moving the nav drawer fragment to the same position that you've your new nav drawer now using, remove the gravity and visibility attributes and using isAndroidTV() method insider isDrawerOpen() (not sure what you want to return though true/false try and see the difference) inside NavigationDrawerFragment to avoid ever calling mDrawerLayout.isDrawerOpen() which will crash the app.

and with that, you wont need to setup the actionbar, since NavigationDrawerFragment.setup does that.

**Comment by LoungeKatt** [comment]
I appreciate your thoughts without having hardware to verify, but this isn't a pull request. You are making the false assumption that it is just about "having the drawer open all the time" when you should know (having made the drawer) it is a frame that goes over the view.

Rather than writing an obscene amount of code and adjustments and more code and more adjustments like the navbar, I went the route of making a simple layout that runs instead. Setting up the ActionBar once is still about 100 lines of code less than whatever you had in mind.

**Comment by SuicideIsPainless** [comment]
Yeah, I agree with @LoungeKatt on this. Changing the navigation background is much more efficient.

**Comment by LoungeKatt** [comment]
That said, it was also only a test of whether it made sense to even use the current implementation of the ActionBar. Honestly, even that was a giant waste of code and resources.

https://github.com/AbandonedCart/Play-/commit/b075365a4ace93caa3b29f027de141604fd4413e is much more efficient and does the same task.
