### ISSUE TITLE
Chessmaster Hangs on Boot.(Probably VU Issues)

### ISSUE THREAD

**Issue by Nobbs66** [jpd002/Play-#303]
Chessmaster fails to boot and just hangs at a black screen. If I can help with more testing, please let me know.

**Comment by NormalSpeed** [comment]
I don't think this is of your skill level ... shouldn't you try CHIP-8 emulation first?

The best way to help would be by not bringing your PCSX2 background to a project that wants to improve.

**Comment by jpd002** [comment]
It's SLUS-20637? I can take a quick look to see what's wrong.

**Comment by NormalSpeed** [comment]
@jpd002 I don't think you understand @Nobbs66 intentions. He is only here trying to help because I took a hit on PCSX2 as an emulator. He isn't here to legitimately help and he doesn't even know how to.

All I'm doing is letting you know that his whole purpose of being here is not legitimate. Check my post -- he didn't come here until I called PCSX2 out. He doesn't even know how the VUs work in PS2.

**Comment by Nobbs66** [comment]
He's trying to harass the pcsx2 devs and testers. 

Anyways, that is indeed the correct game.

**Comment by NormalSpeed** [comment]
Nope. I simply pointed out the flaws with PCSX2 and the truth about @Nobbs66 .

Notice he just closed the issue and reopened it? He's not legit ... at all. He didn't come here to help -- he came here to be a prick and try and show me up.

**Comment by jpd002** [comment]
@NormalSpeed Please keep it cool, I don't think he wants to sabotage the project or anything. It's ok to report problems. I also doubt this is related to VU emulation, but it's ok for people to speculate on possible causes.

**Comment by NormalSpeed** [comment]
@jpd002 I am in no way trying to be trouble here ... I just am not going to let @Nobbs66 try and show me up like this. Sorry for being a bother and I will keep it cool. I realize he doesn't want to sabotage the project, but he didn't come here with good intentions and I can assure you that he only came here to post this because of what I told him about PCSX2 falling behind. That's all.

**Comment by Nobbs66** [comment]
Also, it is correct that pcsx2 can barely handle it with vu1  being emulated with the intepreter rather than either of the JIT recompilers. I figured it's best to help another project since it can only improve ps2 emulation as a whole.

**Comment by NormalSpeed** [comment]
@Nobbs66 I understand ... but try and help when you want to, and not in response to what I say.

It's not of good intentions to run over here and open an issue and try to show me up.

**Comment by Nobbs66** [comment]
I have a screenshot of your commen on my laptop, so dont even lie about it. Anyways, I'm more than to willing to help in any way i can. If you would rather I leave,  then  I will.  Otherwise ill start ripping all of my games in the morning

**Comment by NormalSpeed** [comment]
@Nobbs66 In my say, I'd rather you leave, yeah. Not in my power to enforce, but I really suggest it.

Anyways, the problem with the game is it gets stuck at OsWaitSemaphore 0x00111528 @ JR RA opcode.

**Comment by jpd002** [comment]
@NormalSpeed I think the more people we have, the better this project will be. So, I'm quite glad to see people like @Nobbs66 contributing to this project.

If it's stuck in WaitSema on the EE side, it probably means that a SIF command didn't execute properly.

**Comment by SuicideIsPainless** [comment]
@jpd002 Yeah, that's the same thing I thought from the error. I'm testing it on Visual Studio now.

**Comment by Nobbs66** [comment]
It was just to prove what was said to the pcsx2 devs. 

Anyways ill have to do some reading on my ps2 docs this week, but im more than happy to test while I try to get up to speed on the hardware.

**Comment by SuicideIsPainless** [comment]
@Nobbs66 I see, but we've already had trouble with trolls here before and it might be better suited to post elsewhere. This is about issues relating to Play not PCSX2 or their developers. This isn't a blog.

**Comment by Nobbs66** [comment]
I didbt mean to cause any trouble. I guess ill just escort myself out.

**Comment by jpd002** [comment]
@SuicideIsPainless You don't have your say about who should stay and who leave. Please refrain from posting that kind of message. Keep it focused on the project.

@Nobbs66 You're not causing any trouble, feel free to report any problems you might encounter while testing the emulator.

**Comment by Nobbs66** [comment]
Ok ill get testing in 4 hots or so

**Comment by SuicideIsPainless** [comment]
@jpd002 You keep quiet; this is not your problem.

@Nobbs66 You are unwelcome here and you always will be ... because I say so; doesn't matter what Jean says. I can't stop anyone from doing anything, but I definitely can make problems. If you stay, problems such as preventing issue reports ... entries to the Wikis ... and related such ... can happen.

**Comment by jpd002** [comment]
@Nobbs66 Not really. Updating the compatible games wiki page (https://github.com/jpd002/Play-/wiki/Compatible-games) is usually the way to go.

**Comment by Nobbs66** [comment]
This isn't really related to the game directly, but I'm wondering where VU1 is being handled in the code.

**Comment by jpd002** [comment]
@Nobbs66 Thanks for your updates to the compatibility list! What do you mean by "VU1" exactly? Are you talking about the VIF or the CPU core that executes micro-programs?

**Comment by Nobbs66** [comment]
I'm talking about execution core for micro programs. Lately, I've been interested in studying the micro mode instructions and I wouldn't mind seeing if I could possibly improve their emulation.

**Comment by jpd002** [comment]
Most of the VU instruction emulation happens in here: https://github.com/jpd002/Play-/blob/master/Source/ee/VUShared.cpp

**Comment by Nobbs66** [comment]
I see some areas I could improve on. The XGKICK instruction will probably be my first target. It has some quirks that go along with it.

**Comment by johnnyleap** [comment]
Game has no issues with the VUs that would prevent it from booting (Also, I doubt VU issues in the micro-mode pipeline would have little if any bearing on most games showing an intro or such). @Nobbs66 XGKICK has no real quirks. The command is to send GIF tags to the GS using DMA. There are only few ways this is done, and very little area of quirks in which the instruction can be executed. The biggest quirks in PS2 hardware comes from clipping, rounding (FPU), SIF, and maybe the GS too.

**Comment by jpd002** [comment]
AFAIK, a big part of game booting issues come from missing or buggy stuff in IOP HLE.

**Comment by johnnyleap** [comment]
I'm a bit unsure on how/why the IOP would affect games from booting either, unless it's on purpose. The IOP has no direct impact on anything other than I/O interfaces and the main core. I figured game developers would use the IOP to check versions, controllers, disk, etc. (with .IRX files) with BIOS and that's it. I have no solid clue on how Play! and its virtual kernel environment handles the PS2 BIOS from a high-level, but unless it's the way Play! handles DMA/SIF that would affect it, games should at least show something unless they specifically have issues with the transfer process.

**Comment by johnnyleap** [comment]
I'm a bit unsure on how/why the IOP would affect games from booting either, unless it's on purpose. The IOP has no direct impact on anything other than I/O interfaces and the main core. I figured game developers would use the IOP to check versions, controllers, disk, etc. (with .IRX files) with BIOS and that's it. I have no solid clue on how Play! and its virtual kernel environment handles the PS2 BIOS from a high-level, but unless it's the way Play! handles DMA/SIF that would affect it, games should at least show something unless they specifically have issues with the transfer process.

**Comment by jpd002** [comment]
Play! tries to emulate all of the built-in IOP modules (thbase, thsema, intrman, timrman, cdvdman, sysclib, etc.), but many functions are still missing, preventing IOP modules that come from games from working properly. Threading scheduling is also inaccurate and doesn't handle some of the wait states properly. 

For example, many games will hang because a SIF RPC call doesn't get processed because the IOP is busy doing something else due to a threading bug.

**Comment by johnnyleap** [comment]
Yeah, after inspecting it seems you're right about the IOP, as I've debugged many games that either don't show anything or are showing just an intro or such and hang soon after. Examples:

Grand Theft Auto: Vice City (SLUS-20552) -- Menu/Title Screen only

Last items on IOP call stack: ADDIU V0, R0, $0669 and ADDIU V0, R0, $0666

Also, numerous padman threads stuck waiting with LW opcodes and the cdvd_stream is stuck on LUI.

For Persona 3 FES, the issue seems to be with the Emotion Engine, and Chessmaster is IOP too.

I don't know if it's worth posting more info about the games here or not though.

**Comment by jpd002** [comment]
@johnnyleap Thanks for looking into those games! I've got a branch that allows GTA: San Andreas to get in game somehow (it's not playable yet thought) and it might allow GTA: Vice City to get further too.

As for posting more info, I think it's worth it because I don't have all the games and it might help to classify problems. But I think it should be done in issues that are related to specific games. Posting information about Chessmaster here would be fine, information about Persona 3 FES should be posted in its own issue.

**Comment by Fadi5555** [comment]
What about crash bandicoot the warh of cortex?
It black screen can we get it to in game?

**Comment by johnnyleap** [comment]
@jpd002 Got it! I'll only post relevant info on relevant issue topics. Is the Gregory Horror Show branch the same one that San Andreas works on, or is the branch you're talking about elsewhere?

@Fadi5555 I provided some minor info about the possible cause of Wrath of Cortex not working here: https://github.com/jpd002/Play-/issues/101#issuecomment-139971903

**Comment by jpd002** [comment]
@johnnyleap It's a branch that's local to my PC and that I haven't merged yet. I'm planning to merge it this week.

**Comment by boberto5888** [comment]
Think this issue can be closed as it's been able to go ingame since https://github.com/jpd002/Play-/commit/083c4b3966b829c5a2a2895cd4bd5380ed6bc26b.

jpd002/Play-Compatibility#630
