### ISSUE TITLE
Android port

### ISSUE THREAD

**Issue by collm109** [jpd002/Play-#31]
When will their be an android build, even a beta or alpha build would be nice :)
I have the nvidia shield portable so it might run even if it will be very slow.

**Comment by mantlebreath** [comment]
It only runs homebrew so far, so power isn't much of a demand yet. When a first commercial game boots, that's when the real test of power comes into play (no pun intended) and you can see how well the performance would be. 

So an Android build now won't be very useful to end-users just wanting to load a PS2 ISO and start playing games, because that time isn't yet, and there's still more improvements needed for the graphics emulation.

**Comment by jpd002** [comment]
Yes, the Android port is currently in development, @mantlebreath pretty much summed up the status of the port.

Closing this issue as there is already one (#7) dedicated to the Android port.
