### ISSUE TITLE
GNU/Linux Support

### ISSUE THREAD

**Issue by 3kinox** [jpd002/Play-#318]
Hey,
Is there any linux support ongoing or planned? I guess your renderer is GL/GLES based since android and OSX ire supported right?
Are there any particular blockers for linux build? Something we can help with? Since it runs on OSX must be quite near I guess, something like UI?
BTW, do you support 64bit? I don't seem to see any asm bits, are code emiter that are host specific.
Overall your code looks quite clean, quite nice, if linux is possible I would be very happy to help(also, if anyone else has already worked on it...)

**Comment by jpd002** [comment]
Yes, I'm planning to add Linux to the supported platforms at some point. There has been some work done by @Alloyed to make the emulator compile a standard Unix box (https://github.com/jpd002/Play-/pull/314), but I didn't have time to check out his work yet. I don't think it would be too hard to make it work completely on Linux though.

And yes, x86-64 is supported, but there might be some tweaks to do inside the code generator to properly support the ABI.

**Comment by 3kinox** [comment]
Ok, I am looking around the project. I will try it, and see if I can help for failing tests. 
BIOS/ROM is HLE too? 
I see the code gen seems to be completely separate too, how nice :)
There is some kind of IR? You generate code with standard constraint, like SSA?(I did not yet look inside code gen, mostly structure for now).
If you need help with IR parts, IRs are my life, register allocation and such optimizations are also an important part of it, or at least of my readings and work ;)
For plugins, you are compatible with pcsx2? GSDx OGL/liux is in very nice shape now. Factorizing work with it would be quite nice I guess, the more work goes in the same sense, the better. I see a branch name gregory, is it for gregory hainaut?

**Comment by jpd002** [comment]
Yes, the kernel is done in HLE. No BIOS is required.

The code generator does have its internal IR. It also uses a kind of SSA form to do its optimizations. The register allocator would definitively need some more love because it doesn't generate the best results.

Play! is not compatible with PCSX2 plugins. The gregory branch contains the changes needed to make Gregory's Horror Show boot.

**Comment by forcejackson** [comment]
Any chance we can see a Linux build sometime next month, maybe?

My other PC is a Linux machine and I'd do the deed of testing compatibility and even GUI stuff later on when I can manage a build or instructions on how to build for Linux.

**Comment by jpd002** [comment]
Can't guarantee anything for next month, but I've been working on making things work on Linux and FreeBSD. I'll probably merge @Alloyed's PRs very soon as I've got almost everything working on my side.

**Comment by maximu** [comment]
Compile are fine or are incomplete? 

I have some issues when search pthread_create - not found

maybe cmake bug? I use archlinux

**Comment by jpd002** [comment]
I got it to compile and link on FreeBSD as of today. What's the error you're getting?

**Comment by maximu** [comment]
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring incomplete, errors occurred!

No detected  undefined reference `pthread_create'

but the pthread library is found at:
$ locate libpthread
/usr/lib/libpthread-2.21.so
/usr/lib/libpthread.a
/usr/lib/libpthread.so
/usr/lib/libpthread.so.0
/usr/lib/libpthread_nonshared.a

the parameter -lpthreads has an 's' too many maybe this a problem?

**Comment by Thunder07** [comment]
I was looking into how i could add a linux UI for Play! since we can already compile the project for linux and to my surprise how ready everything was, if anything this is a testomy to how clean the code is written, just few lines to create a OpenGL window and the emulator was alive.

if you'd like to test it, you can just try this [branch](https://github.com/Thunder07/Play-/tree/unix_ui
),
you'd need few more libraries which you can get with (ubuntu):
`sudo apt-get install libglfw3-dev libmysqlclient-dev libbz2-dev libglew-dev -y;`

note, that although libglfw3-dev is going to be installed, this won't work, but this will get us the dependencies required to build the source from github

```
git clone https://github.com/glfw/glfw.git
cd glfw
mkdir glfw-build
cd glfw-build
make ..

make
sudo make install
```

if this is still failing due to dependencies this should help
`sudo apt-get install xorg-dev libglu1-mesa-dev`
on Ubuntu 16.04 this wasnt needed (maybe i installed it earlier) but on a fresh Ubuntu 14.10 LTS it was needed

cd Play-Build/Play/build_unix/
./build.sh
./build/mainui

this is very permeative, i've 'hacked' a way to add some control to see how far into the game this would run and everything seems in order so far, I couldn't figure out how to use the current method with glfw, so i found it easier to do this for now, currently the location to iso is hard coded, so you'd need to edit that to find your game.

although this isn't my area of programming, summer break soon and i plan on doing a lot of reading in regards to this area in an attempt to get a linux client up to current standard.

[FFXII](https://cloud.githubusercontent.com/assets/5013823/14577950/d394f034-0373-11e6-9616-4625b3a0d088.png)
[FFXII some rendering issue](https://cloud.githubusercontent.com/assets/5013823/14577952/d3db7cde-0373-11e6-9289-2d334ed83c3a.png)
FFXII ran with a slow FPS, nothing to surprising, but navigating the menus, 2D, was really smooth,
considering that, i know you've been testing Oden Sphere a lot, and its a 2D game, so i gave it a go, and it ran really well.
[Oden Sphere](https://cloud.githubusercontent.com/assets/5013823/14577951/d3c3f9e2-0373-11e6-8040-88c1c6949cab.png)

**Comment by jpd002** [comment]
Nice work! I have a Qt UI in the works (it's incomplete and haven't touched it recently though), but I've only got rendering working so far (no input at the moment). I will push my branch later.

**Comment by Thunder07** [comment]
Qt isn't a bad idea, since it's cross platform, you can eventually have a single uniform UI between linux/osx/windows.

**Comment by Thunder07** [comment]
whenever I'm free, I've been experimenting with the UI.
I tried Qt and WxWidgets, both with similar results, that is, I couldn't use their native OpenGL widget with Play, both similar problem, in that Play! OpenGL rendering thread seems to start (printf insider PresentBackbuffer()), but nothing would display on the widget, however, using something such as xcreatewindow which created a completely different window works, but you end up with something like PCSX2, with 1 window with the menu bar, another for rendering and a 3rd for logging. since thats all back to personal preference, and if this is what you're going for then fine.

personally I'd prefer to have menu bar and rendering onto the 1 window, (and maybe a separate logger if you want one), and i managed to get that to work, although, this seems to be a bit 'hacky' but i also think it's a reasonable way to get it done, i basically added a wxglcanvas, but that also works with wxwindow, using the same method as i would when creating a new window (xcreatewindow), ill just substitute calling xcreatewindow with the window handler of wxglcanvas.

[wxwidget](https://cloud.githubusercontent.com/assets/5013823/14763032/c231ee32-0981-11e6-80fe-17802c87cde1.png)

I'd say this would work the same with Qt as well, but I've noticed that a lot of the emulators are using wxWidget over qt, perhaps because you can just skip the IDE which is 700mb big.

**Comment by jpd002** [comment]
I ran into the same problem while experimenting with Qt. I had to go through some hoops to get the emulator's OpenGL output to display inside a Qt window, but it works fine. I was also able to create a Vulkan swap chain hosted in a QWindow.

I haven't tried wxWidgets but I don't have a preference for Qt over wxWidgets. I think it would be as good as Qt if it's also possible to create a Vulkan swap chain hosted in a wxWidgets widget. 

My only requirement would be to have everything inside a single window (like you mentioned: menubar + rendering as one window).

**Comment by Thunder07** [comment]
I'd imagine you're still using the same GSH_OpenGL class format for vulkan, at which i see no reason why it wouldn't also work with WxWidgets.

but in the long run, i don't think either or will really make much difference, and few gb these days shouldn't really be a deal breaker.
so to list few pros and cons and to be honest, they seem rather subjective.

Qt
- IDE+Debugger is a small bonus if needed, though i don't see a complex design to justify it either.
- Size 700mb+
- include collision? (due to class extension)
- Multiplatform.

WxWidgets
- Small size 100mb
- no include collision
- No IDE or Debugger
- Multiplatform.
https://wiki.wxwidgets.org/WxWidgets_Compared_To_Other_Toolkits#Qt

I'll push my work of wxwidgetx to a separate branch so you can compare how they both work, around this time tomorrow night hopefully.

**Comment by jpd002** [comment]
It's a bit different, you need an `xcb_connection_t*` and `xcb_window_t` to create the Vulkan swap chain. Qt provides a pointer to the connection through QX11Info and the window can be obtained by casting a QWindow's winId member.

**Comment by Thunder07** [comment]
```
Display * m_display = XOpenDisplay(NULL); // will work on independent of Qt/WxWidget
//xcb_connection_t *m_ xcb_connection_t = xcb_connect (NULL, NULL);  // will also work on independent of Qt/WxWidget

Window m_window = (Window)GDK_WINDOW_XID(gtk_widget_get_window((GtkWidget*) glcanvas->GetHandle()));
//xcb_window_t m_ xcb_window_t = (xcb_window_t)GDK_WINDOW_XID(gtk_widget_get_window((GtkWidget*)glcanvas->GetHandle()));

//GDK_WINDOW_XID returns XID which can be casted to either types

glXSwapBuffers(m_display, m_window); //<-- this is what I'm doing in wxwidget which is actually independent of Qt/WxWidget
```
passing `xcb_window_t / Window` to `CGSH_OpenGLUnix::GetFactoryFunction()` will allow you to keep the context creation and swap completely independent of Qt/WxWidget as well.

> [Link:] (https://xcb.freedesktop.org/MixingCalls/)You can now mix calls to XCB and Xlib. The datatypes of the two systems are somewhat interoperable; for example, you can use an Xlib Window anywhere an xcb_window_t is required. In general, XID types like Window (X.h:typedef XID) are synonymous with their XCB equivalents.

More: https://xcb.freedesktop.org/xlibtoxcbtranslationguide/

**Comment by jpd002** [comment]
Thanks! Can't really build it at the moment, but I'll take a look this week-end when I get back home.

**Comment by Thunder07** [comment]
to have an educated opinion about Qt vs widgets, I've setup qt and started working on the UI.
needless to say, I found it much easier working with qt, because of the IDE, so much so, I ended up continuing the work until i got a working settings dialog. the ui can also be built using IDE or terminal.

you can find qt branch [here](https://github.com/Thunder07/Play-/tree/unix_ui_qt) and I'll send a PR tomorrow or the day after, after I prepare a small write up of the needed packages for the build.

**Comment by ProfessorKaos64** [comment]
Does the Unix/Linux build require a minimum versions of standards? (-DCMAKE_CXX_FLAGS="-O2 -g -stdlib=libc++"). Build log: http://sprunge.us/TiEY

**Comment by Thunder07** [comment]
I'm not sure whats causing your error, i couldn't find any reference to change in static_assert between 4.9 and 5.4, however, I couldn't get travis to work using [gcc 4.8.4](https://travis-ci.org/Thunder07/Play-/builds/158858387) but worked with [gcc 5.4](https://travis-ci.org/Thunder07/Play-/builds/159119132), they're different errors but perhaps its worth a shot.

**Comment by ProfessorKaos64** [comment]
Debian Jessie is way old with gcc unfortunately, but I play on putting together a test Arch Linux AUR package as well. I wonder if this will build ok with clang/clang++?

**Comment by Thunder07** [comment]
@jpd002 last commit to master was "fix build on clang", so I guess it would. 
I know Ubuntu has a test repo with upto date gcc for older distros, maybe debian does too?

**Comment by ProfessorKaos64** [comment]
Yea using clang seems to do the trick for those not on GCC5. I'll know if GCC5 is good as well when I test out an AUR package. See [debian/rules](https://github.com/ProfessorKaos64/LibreGeek-Packaging/blob/brewmaster/play/debian/rules) for Debian' folk.

**Comment by ProfessorKaos64** [comment]
Ok, built the project with clang 3.8. Is ./Play/build-ui/Play-Ui the executable/binary I am looking for? Do I need to include any other directories for run-time?

**Comment by Thunder07** [comment]
Ya that's it, what do you mean by other directories?
That's the only bin you'd need, framework, CodeGen, play library are all statically linked, I think qt and boost are dynamically linked.

**Comment by ProfessorKaos64** [comment]
If they are staic, that's what I mean, if installed to /usr/games or /usr/bin, I might need to include those directories in /usr/share/games/play for modular use.

**Comment by Thunder07** [comment]
You can use ldd to confirm the dependencies.

**Comment by ProfessorKaos64** [comment]
Oh I know that part, i meant more along the lines of assets. I typically like lddtree for lib checks.

**Comment by jpd002** [comment]
Closing this, the Linux port is working now.
