### ISSUE TITLE
Unable to boot any games on OSX

### ISSUE THREAD

**Issue by CarterLi** [jpd002/Play-#32]
1. Open Play! on OSX 10.10.2
2. File -> Boot Disk Image...
3. Select a rom (ISO format)

Get an error: Load ELF error
![image](https://cloud.githubusercontent.com/assets/6134068/6917277/b69ac26c-d7d5-11e4-8b27-1e20520b5ed0.png)

Am I doing something wrong?

**Comment by murphytex** [comment]
Hi !
Same problem for me (osx yosemite - haswell GPU)
But thank you for porting it to mac anyway.

**Comment by Xiaomita** [comment]
Maybe the ISO is broken somehow? Verifying MD5 checksum or such could help. I heard something similar about PCSX2 where the issue could be the relative path to the ISO causing problems (then again this is not PCSX2). Try other ISO files if you have them to see if it's only 1 ISO or others maybe.

**Comment by vgturtle127** [comment]
I have seen this with PS1 emulators occasionally.

It is usually either a corrupted disc image, a compressed disc image, BIOS issues, or in rare cases something wrong with the emulator.

However, since games seem to work fine on other platforms, it could also be a Mac regression or something.

Another thing that just came to my mind is that maybe Mac OS X tries to read the images before they are put into the emulator, and that causes corruption. Maybe it tries to detect what it is, and then chooses the wrong file type? Not sure. Need more information and testing. I don't have a Mac (maybe somebody could donate one?), but I could try to run it in a virtual machine when I get my development machine running.

**Comment by jpd002** [comment]
My bad actually, I screwed something up in the disk image loading code. Easy fix, it's in the repo now.

Here's a new build with the problem fixed:
http://purei.org/downloads/play/temp/Play-20150331-IsoReadFix.dmg

**Comment by CarterLi** [comment]
Thanks for the quick fix, man!
Tested some games:
1. KOFXI: Playable, with graphics glitches and no sound
![image](https://cloud.githubusercontent.com/assets/6134068/6939529/15d152bc-d8a0-11e4-9671-f2f14a7c469a.png)

2. Mega Man X8: Black screen

3. Raiden III: Load ELF error

**Comment by Xiaomita** [comment]
@CarterLi They can be added to the compatibility list: https://github.com/jpd002/Play-/wiki/Compatible-games
