### ISSUE TITLE
final fantasy 10

### ISSUE THREAD

**Issue by bahamut87** [jpd002/Play-#335]
Hi . i play at final fantasy 10 on m'y xiaomi mi 3 and i ask you à question ? Maby one day we can play at 50 fps and whith song ? I play at 4 fps. Thanks for respond ;)

**Comment by bahamut87** [comment]
Im french soory for m'y bad english

**Comment by johnnyleap** [comment]
This issue isn't really FFX specific as all games will run below fullspeed currently on any ARM processor since they aren't fast enough and the emulator is too demanding at the moment. Even on Intel CPUs it takes very powerful processors to play FFX around fullspeed. This seems more like two general issues: lack of sound on Android and the emulator being too CPU intensive for most systems.

As for the sound issue, you can open a new issue about sound output on Android maybe and that might be better, and maybe another issue about improving the speed/optimization of the emulator.

I just don't see this as a good issue because it pertains only to one game and anything that'd make FFX run 50 FPS on a Xiaomi Mi 3 is probably a bigger optimization that would not be just for one game.

**Comment by jpd002** [comment]
@bahamut87 Désolé, je ne crois pas que ça sera possible de jouer à FFX sur un Xiaomi Mi 3. Comme @johnnyleap a mentionné, l’émulateur a déjà du mal à bien fonctionner sur PC. Il y a encore beaucoup d'optimisation à faire, mais je ne pense pas qu'on se rende à un frame rate élevé sur Xiaomi Mi 3.
