### ISSUE TITLE
Testing PS2 Games On GBox (Android Device)

### ISSUE THREAD

**Issue by Excisions** [jpd002/Play-#336]
Going to be testing a bunch of games to help out.

Android Device: GBox Q
Weekly Build: Oct 11

Will be updating the list periodically after testing games in my current library

List of Games & Errors (If applicable):

Sly Cooper 3: Honor Among Thieves - Game does not run at all, app crashes
Date tested: 10/14/15

Yu-Gi-Oh! Capsule Monsters Coliseum - Game does not run at all, app crashes
Date tested: 10/14/15

**Comment by jpd002** [comment]
Thanks for the compatibility reports! Don't hesitate to update the official compatibility list with your findings: https://github.com/jpd002/Play-/wiki/Compatible-games.

**Comment by johnnyleap** [comment]
G Box Q supports OpenGL ES 3.0? From its site, it uses the Mali-450, which only supports 2.0.

In that case, will any game work? Or do I have something wrong? Play! requires OpenGL ES 3.0.

**Comment by jpd002** [comment]
@johnnyleap You are right about Play! requiring an OpenGL ES 3.0 compatible device. I don't know exactly what happens if you try to use the emulator on a device that doesn't support it, but it might possibly crash at some point. I guess I should add something notifying the user if he tries to run the emulator on a non GLES 3.0+ compatible device.

Closing this for now. If OP posts a call stack, I'll take a look to see if the crashes are due to GLES's version.
