### ISSUE TITLE
spongebob squarepants the movie ISO Stops working after the loading screen

### ISSUE THREAD

**Issue by Isov91** [jpd002/Play-#341]
<b> My device is sony xperia z2 d6503 and android version is 5.1.1 Not rotted its stock phone.
Cpu if it is nessecary  2.3 GHz Qualcomm MSM8974AB Quad-core with 3gb ram using Adreno 330 as GPU<b>

So I thought I try this game on the emulator and the results were bad. First, once you start the game you wait like 5-10 seconds for the game to process opening. Then the game starts up and shows up the info and trademark stuff so far so good. Next I get is the loading screen. Nothing again wrong so far just slow fps so far and when the loading screen ends I get to a screen and dont know how to describe it. Heres some screenshots I took of it. The pictures goes in order what happens

![2015-10-28 - 1](https://cloud.githubusercontent.com/assets/15370243/10804903/47ec9b6a-7dca-11e5-83b1-b238b101ea00.png)

![2015-10-28 - 2](https://cloud.githubusercontent.com/assets/15370243/10804904/47ecfbaa-7dca-11e5-9199-9c355f6172f1.png)

![2015-10-28 - 3](https://cloud.githubusercontent.com/assets/15370243/10804902/47e9791c-7dca-11e5-9a46-83827649aa04.png)

<b> And thats all information I can give from my expirence from here <b> The app or game didint crash on me so I dont know if error file was sended to the dev.

**Comment by jpd002** [comment]
Thanks for the report. Looks like an issue with MPEG decoding which happens in some other games (like Kingdom Hearts' intro for example).

**Comment by johnnyleap** [comment]
Possibly the T.H.Q./Nickelodeon video(s) that come out right after? Does it eventually get through it if you wait long enough/press a button? It could just be the videos playing fine (though clearly not rendering fine, but that's a different story) and waiting a minute or two to get past, or does it freeze?

**Comment by Isov91** [comment]
@Johnnyleap maybe you're right. Let me test it and I brb

**Comment by Isov91** [comment]
@johnnyleap ok i got it. This is what I got. After the green screen thing play crashed there. 
![screenshot_2015-10-29-14-04-38](https://cloud.githubusercontent.com/assets/15370243/10819030/31317982-7e46-11e5-9a88-1f9cd1b5633a.png)

![screenshot_2015-10-29-14-02-40](https://cloud.githubusercontent.com/assets/15370243/10819029/3130de28-7e46-11e5-9af3-99932c71b4f4.png)

![screenshot_2015-10-29-14-02-25](https://cloud.githubusercontent.com/assets/15370243/10819031/3134556c-7e46-11e5-8562-bdad5378beed.png)

**Comment by reinventedz** [comment]
Did a little research with this game and found that on Windows it goes further than on Android and actually gets to the title screen and passes those movies (for whatever reasons, but that's different):
![1proospon](https://cloud.githubusercontent.com/assets/15336924/11018831/8fbcf7e4-85d3-11e5-9340-2476ecca28d6.jpg)
![2proospon](https://cloud.githubusercontent.com/assets/15336924/11018832/922f9fb8-85d3-11e5-9a65-fd863edfd88f.jpg)

But this is where the issue begins ... after waiting on the second screen, the game will then hang (not crash ... just hang/freeze and the FPS will fly up to the hundreds) and the issue seems identical to PCSX2's since PCSX2 cannot run this game either without a PNACH file (patch) which does the following:

(on the Europe version; I only have the US/North American version & it doesn't work for me)

Changes EE RAM at address - > 0010f3e0 to -> 0000000 (seems to clear it)

What this apparently does is let it continue on PCSX2 ... so, this is probably the same for Play!

What does this address contain in RAM at the point of freeze? Seems to be: "mfc0 v1,Status"

Seems to be an interrupt involving COP0 and a transfer to v1 from register "Status," which seems to be one of the exception handling registers of the MIPS architecture. Don't know about Play!, but a few years ago PCSX2 very poorly emulated COP0 & could explain why some opcodes/interrupts failed.

This probably also involves "syscall" instructions on MIPS too since this is for exception handling.

That's about all I know, so i hope it is somewhat useful for reference at least.

**Comment by atomic83GitHub** [comment]
A fix is available for this game in PCSX2, what is your game version?

**Comment by atomic83GitHub** [comment]
This game now go ingame with the master branch, close the issue.
