### ISSUE TITLE
External controller support

### ISSUE THREAD

**Issue by bobbymc1985** [jpd002/Play-#345]
Im getting my nexus 9 soon and also getting the ipega 9203 when would we expect external support for these controllers or even ps3 ones

**Comment by LinkofHyrule89** [comment]
The app already has controller support not sure why this is still open.

**Comment by bobbymc1985** [comment]
Ive tried my ipega bluetooth controller and it didnt work.i will try again, as im going to be testing a few more games.

**Comment by LinkofHyrule89** [comment]
It must be something with your controller because it works fine with my MadCatz controller. I think that those ipega controllers seem to have problems with app compatibility in general but I could be wrong about that. There wasn't previously a standard way for controllers to interface with apps but that problem has been fixed and those controllers might not meet the new specifications.

**Comment by KinCoded** [comment]
I have an ipega and am willing to test stuff. The ipega has 3 modes: gamepad mode (where buttons correspond to gamepad buttons), keyboard mode (where buttons correspond to keyboard buttons and will input text if you press them in a text box, but the analog sticks become digital input only, and i vaguely remember having input issues where holding a button counts as clicking it multiple times like what would happen on a keyboard) and a third one that i think was mouse and keyboard mode but i never got that one to work.

If a button mapping menu is implemented I'm sure it'll be possible to at least get keyboard mode working.

**Comment by atomic83GitHub** [comment]
This is a duplicate issue.

**Comment by Zer0xFF** [comment]
duplicate of #73
