### ISSUE TITLE
Alpha blending doesn't quite work in Budokai 3's BANDAI logo

### ISSUE THREAD

**Issue by MoochMcGee** [jpd002/Play-#355]
https://mega.nz/#!RhciATAB!EVaKnc3V2JR5eFfK9O37bMVwAEz87MTR-QxaBTa9MIE

In the framedump, everything appears fine. However, in the emulator: 

![playissue](https://cloud.githubusercontent.com/assets/956763/11664131/934b4304-9da5-11e5-919a-cc5c165db68c.PNG)

**Comment by MoochMcGee** [comment]
To fix this, I suggest implementing blending in a fragment shader, similarly to how Dolphin and PCSX2 do it.

**Comment by bigianb** [comment]
The difference in the frame debugger and the actual emulator is probably due to them using different GS implementations. The emulator uses the openGL one and the frame debugger uses the DirectX implementation. That's obviously not ideal, but it is what it is.

**Comment by jpd002** [comment]
Thanks for reporting this. Handling of color combine modes and alpha blending is kinda screwed up at the moment. As @bigianb said, the frame debugger uses DirectX while the emulator itself uses OpenGL, which might explain why you get two different results. 

I'm currently working on a "unified OpenGL" (same code for desktop and mobile) branch and I've already made some improvements to the way vertex colors are combined with texture colors to better match the PS2's output (https://github.com/jpd002/Play-/tree/common_ogl). You can try the game with that branch to see if it fixes this particular issue.

Alpha blending in shaders will be necessary to emulate some of the more "exotic" blending formulas and to emulate the lack of color clamping (which can be enabled or disabled by setting a register). But alpha blending in shaders is quite tricky, especially on desktop since you have to use the texture barrier extension which is no fun to use.

**Comment by jpd002** [comment]
Closing, this now works fine on the current version.
