### ISSUE TITLE
Android build doesn't appear to work on Marshmallow/6.0.x

### ISSUE THREAD

**Issue by willcast** [jpd002/Play-#369]
The 20151220 build of rhe emulator crashes immediately after being selected from the launcher on both Marshmallow devices that I have tried. 

Here's the logcat from an NVidia Shield K1 tablet running the official Marshmallow OTA released earlier this week:
http://pastebin.com/R4yjZfpL

And here is another logcat from an Asus ZenFone 2 Z00A running CyanogenMod 13 nightlies (it's on 6.0.1): 
http://pastebin.com/BSgx9hR7

Same symptoms on both. I have never previously installed the emulator on either device.
Let me know if I can be of any more help.

**Comment by jpd002** [comment]
Thanks for reporting this. I'll try to find an Android 6 device to test on and see why that crash is happening.

**Comment by Thunder07** [comment]
Unfortunately, there is no stable android M for my device to test it, but if I had to guess, the crashes are probably due to the new permission system, and since you're now compiling using api-23 without implementing the new system it crashes anytime it attempts (let's say)  access sdcard, Internet etc. 


If this is the issue, you could temp fix it by just compiling with api-22 or lower.

**Comment by willcast** [comment]
I don't know Java, but I'm not particularly busy for the foreseeable future. If there's anything more in depth I could do to narrow this down then please lay it on me.

By the way, sorry about the close/reopen thing.

**Comment by willcast** [comment]
Ahh, of course. On the Asus phone, going into App Info and manually granting Storage permission allows the app to launch.

Perhaps there's something passing a NULL into that library because it gets denied when accessing the storage?

**Comment by jpd002** [comment]
The exception most likely comes from here: https://github.com/jpd002/Play-/blob/master/Source/AppConfig.cpp#L8. `EnsurePathExists` is called, but it probably fails because it can't create directories in the device's storage due to not having proper permissions and throws an exception that is not caught by anyone.

So, yeah, I guess we should request for the `android.permission.WRITE_EXTERNAL_STORAGE` permission before attempting to initialize the settings system. Not quite sure what would be the best way to do that since permission request is asynchronous.

**Comment by Thunder07** [comment]
you could remove all the calls in OnCreate() and move them to the callback method onRequestPermissionsResult() continuing the startup process or killing the app, if user reject permission.

Google recommends not requesting a lot of permissions on startup (we only need 3 for Play!, so that should be fine), and at the same time, not requesting them at startup means you'd need to readapt the code to request permission when needed, then handle the request to continue the task it was doing.

in talks of permission, do we actually need MOUNT_UNMOUNT_FILESYSTEMS?

**Comment by jpd002** [comment]
No idea about `MOUNT_UNMOUNT_FILESYSTEMS`, it was added in commit 396d7ae. I'll try removing it to see if it changes anything.

And yeah, might was well change targetSdkVersion to 22 for the time being. Might take some time before I get access to an Android 6.0 device.

**Comment by Thunder07** [comment]
@willcast does the latest update solve the crash issue on Android M, you'd need to install the app and reinstall for an accurate report.
if it doesn't then @jpd002 would need to change the api from here https://github.com/jpd002/Play-/blob/master/build_android/project.properties

**Comment by willcast** [comment]
Yeah, it works now. Sorry I didn't get back to you earlier.
