### ISSUE TITLE
Support for Vulkan?

### ISSUE THREAD

**Issue by ghost** [jpd002/Play-#370]
I am asking this question because i am curious if you will bring support for this api. If you are then how much of an improvement will it have over the standard OpenGl ES?

**Comment by yorkiesandskittles** [comment]
It would be very handy if Play! had its own forum to discuss stuff like
this (like PCSX2 and Dolphin currently do.) While it's certainly a good
question, it's one better suited for a forum, rather than an issue tracker.
Not attacking you or anything, just expressing my interest for something
like that.

**Comment by jpd002** [comment]
Yeah, Vulkan (and Metal on iOS) will be quite useful with games that have an high draw call load. I don't know when it'll be available on Android (I'm guessing sometime next year), but I'll start looking into it when it does.

@yorkiesandskittles Yeah, a forum would be nice for that kind of discussion. I used to have one, but I shut it down because it was quite time consuming to maintain.

**Comment by Abz1** [comment]
@yorkiesandskittles oops sorry about that, i just wanted to ask about Vulkan here, instead of somewhere else because i probably wont get the answer im looking for.

@jpd002 Thats great news! hopefully it wont take long to implement it to the emulator.

**Comment by yorkiesandskittles** [comment]
@Abz1 Like I said, I wasn't attacking you :P

**Comment by Thunder07** [comment]
i found [this](http://blog.imgtec.com/powervr/vulkan-high-efficiency-on-mobile) to be an interesting read for anyone interested.

**Comment by MoochMcGee** [comment]
Why does everybody treat Vulkan like it's already released? It hasn't been released, people. Good god.

**Comment by ADormant** [comment]
@jpd002 
https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#introduction
https://github.com/KhronosGroup
https://www.khronos.org/news/press/khronos-releases-vulkan-1-0-specification
https://www.khronos.org/registry/vulkan/
https://github.com/SaschaWillems/Vulkan
https://github.com/vlj/rpcs3/tree/vulkan
https://developer.nvidia.com/vulkan-android#samples

**Comment by ADormant** [comment]
http://developer.download.nvidia.com/assets/gameworks/downloads/secure/Vulkan_Beta_Drivers/GL_NV_draw_vulkan_image.txt?autho=1455669688_460483b6163765dab8b29fe76145a80e&file=GL_NV_draw_vulkan_image.txt

**Comment by jpd002** [comment]
Yup, time to look at this seriously now that it's officially available.

**Comment by Fadi5555** [comment]
Yeah and don't forget to support metal on ios as well.
And welcome back.

**Comment by ADormant** [comment]
https://github.com/nvpro-pipeline/vkcpp
https://github.com/john-chapman/VulkanTest
https://github.com/mlaveaux/VulkanRenderer
https://github.com/pld-linux/vulkan-loader
https://github.com/FaultyRAM/vulkan-sys
https://github.com/kainino0x/rust-vulkan

**Comment by ADormant** [comment]
https://github.com/tomaka/vulkano

**Comment by LoungeKatt** [comment]
Nobody told @DPersonalized there was an entire Google+ group at https://plus.google.com/communities/116366675710176072922 before letting him play git police without anywhere to direct traffic? Well, there ya go. Better late than never, I suppose.
