### ISSUE TITLE
How do I install iOS version without jailbreaking?

### ISSUE THREAD

**Issue by 10aciousD** [jpd002/Play-#389]
I am trying to get this emulator on my non-jailbroken iPad Air 2 running iOS 9.3.

**Comment by jpd002** [comment]
To get the emulator to work on a non-jailbroken iOS device, you need to start it through Xcode. You will need a valid code signing certificate to be able to do so.

**Comment by 10aciousD** [comment]
Does Xcode work on Windows 10?

**Comment by jpd002** [comment]
You will need OSX to run Xcode.

**Comment by 10aciousD** [comment]
Are there any Xcode alternatives for Windows that I could use?

**Comment by Thunder07** [comment]
nope, Apple are fun like this.

**Comment by Fadi5555** [comment]
@Thunder07 sorry for this dump question. But can you help @jpd002 to show up the boxart of games like on the android version please? but If you don't have an idea to fix this issue it's ok.

**Comment by Thunder07** [comment]
I'd love to but I don't have an iPhone nor do i have the knowledge to program for them, as it stands I can only help with android.

but @Fadi5555 you have to learn to be patient, because this project will take yearS to be developed, and asking once or twice is fine, if you keep doing this people will get offended and annoyed.

You have already gotten multiple answers before, (1) box art are cosmetic and are not a priority (2) current jean is working on adding sound and I'm sure there were other answers as well, jean is aware of it and when he think it's time to look at it, he'll fix it.

**Comment by Fadi5555** [comment]
@Thunder07 first of all thanks for your politeness
And yeah you're absolutely right. I'm really sorry. But all this because of my interest of this amazing project. Even @jpd002 he need to know about the issues on his project only to fix them up. Like any project. I said to help jean because I saw your works on this project a few months ago.
And sorry again if I asked something more than one time. This is only for help.
