### ISSUE TITLE
Tekken 4 - Graphical issues (missing characters / enviroment etc.)

### ISSUE THREAD

**Issue by JohnGodgames** [jpd002/Play-#400]
Tested on **Play-20160417-64**

**Frame dump** [here](https://mega.nz/#!iFdiQJLD!7jrcgXC-xkFkHn-wlmkJyieBvn_GBYO4h8r353OTq_Q)

![tekken 4 play issue 1](https://cloud.githubusercontent.com/assets/11453507/15031466/0d8147e0-1259-11e6-9c76-eb3a3315dd9e.JPG)

![tekken 4 play issue 2](https://cloud.githubusercontent.com/assets/11453507/15031467/11afbb58-1259-11e6-840f-8e8c07b48365.JPG)

![tekken 4 play issue 3](https://cloud.githubusercontent.com/assets/11453507/15031472/1bca3bea-1259-11e6-9541-11e50dba477d.JPG)

**Comment by Fadi5555** [comment]
Hi there it's really nice to see you here.
I know your a famous I mean you have a YouTube channel. And I really like all your videos because it focused on emulators and games like psp,ps2,wii,GameCube and so on.

So any way the creator of this amazing project called @jpd002 and he trying always to increase the compatibility of games as well as fixing the issues.
You can see the compatibility list of games here:
https://github.com/jpd002/Play-/wiki/Compatible-games
Only to see the state of games so far (working in-game or not)

Thanks again for your videos. I like them.

**Comment by JohnGodgames** [comment]
@Fadi5555 Thx...glad to here

Yeah I've looked on compatibility list already.My personal compat. list is here http://tinyurl.com/play-updated-compat

**Comment by Fadi5555** [comment]
I really want from you to test your stuff on jailbroken iOS devices (like iPad Air 2 and up)
Also make videos on that if don't mind.
Thanks again.

**Comment by JohnGodgames** [comment]
I prefer a powerful devices with android.You can take a look at some of my videos [here](https://www.youtube.com/playlist?list=PLbnbApMQwO0ik8_ggNF-lSOwtdfP2KKG8) these are also as reference videos for you @jpd002

**Comment by jpd002** [comment]
Quickly looked at the game in the debugger, looks like it's using unimplemented VU instructions. I'll add them in and see if I get something better.

**Comment by jpd002** [comment]
I've implemented the missing VU instructions and I've also enabled "accurate" alpha testing. I'm getting this result now:

![tekken4_1](https://cloud.githubusercontent.com/assets/6760433/15489930/03306482-2132-11e6-9577-df8312aaa3b3.jpg)

Don't know why the characters don't show up though. It's quite a shame the game relies on "accurate" alpha testing so much, I don't have an efficient implementation for that yet (which is why it's not enabled in the current builds).

**Comment by JohnGodgames** [comment]
@jpd002 That's great.Is there other way than email how to contact you?What about make an IRC channel at freenode (play-ps2-dev)?We can debate there and you can get some attention from other devs...also read [this](https://www.reddit.com/r/emulation/comments/4jyivb/play_ps2_emulator_for_windows_os_x_android_ios/)

**Comment by jpd002** [comment]
Humm, we could try making an IRC channel, but I'm quite busy and I rarely get much time in a steady place (when not at work, I'm often on the run). And thanks for the Reddit thread, I totally agree this project needs more contributors.

**Comment by JohnGodgames** [comment]
@jpd002 I've created one on freenode **play-ps2-dev** so we can communicate and solve problems there.

**Comment by boberto5888** [comment]
> missing characters / enviroment 

This issue was resolved with the merge of the [capcom_classics_2 branch](https://github.com/jpd002/Play-/compare/83cff10280ce...20113e02d244).

![tekken4](https://user-images.githubusercontent.com/22404524/58452015-02816500-80d3-11e9-8dba-5d2ea2360a9f.png)
jpd002/play-compatibility#398

**Comment by jpd002** [comment]
Let's close this as there is a compatibility entry for the game.
