### ISSUE TITLE
LLE mode?

### ISSUE THREAD

**Issue by MoochMcGee** [jpd002/Play-#410]
I'd like there to be a mode that Play! can run in where it runs the BIOS and all IOP modules the way the PS2 did them, and the way that PCSX2 has been doing it since almost the beginning. I have the feeling this would put an end to tons of threading bugs and allow the developers to concentrate on getting things working.

**Comment by jpd002** [comment]
Yeah, it would be possible to disable the HLE kernel and rely only on the BIOS to do things. It would require improvements to emulation of some of the hardware though (SIF comes to mind) because I don't think the BIOS could run in the emulator in its current state.

That said, I agree that the HLE kernel brings its share of problems, but it has improved a lot this past year (big thanks to hardware tests) and it's getting less and less in the way.

**Comment by atomic83GitHub** [comment]
With LLE emulation, users must dump ps2 bios (and some download it), it will be an issue for bug reporting and Legality.
In my opinion, Keep and improve HLE bios can be a very big advantage for Play!.

**Comment by jpd002** [comment]
Closing this, LLE mode is not in the plans for now.

**Comment by mirh** [comment]
Hope fps2bios will come to light one day 🙃

**Comment by mirh** [comment]
@bigianb would you perhaps happen to have any clue about the licensing details and/or authorship of the aforementioned work?
There's quite a bunch of people scared to even look at it, like it was coming from sony or something
