### ISSUE TITLE
Onimusha 2: Samurai's Destiny - Graphical issues (Greenish textures / background...)

### ISSUE THREAD

**Issue by JohnGodgames** [jpd002/Play-#415]
Tested on **Play-20160508-64**

There are also more issues with characters as you can see on the pictures...

**Frame dump** [here](https://mega.nz/#!acNWhTSS!tDajdDdzUgt6wzbpLLrFvB1lUZsREdy-K7wwA7GKj4E)

![onimusha 2 2](https://cloud.githubusercontent.com/assets/11453507/15522466/e41e2840-2212-11e6-9ba2-8f92d7b65872.JPG)

![onimusha 2 1](https://cloud.githubusercontent.com/assets/11453507/15522461/da2bebb0-2212-11e6-8079-be1ec8bdea65.JPG)

![onimusha 2 3](https://cloud.githubusercontent.com/assets/11453507/15522469/eb934088-2212-11e6-9cf5-8b726ea6567f.JPG)

![onimusha 2 4](https://cloud.githubusercontent.com/assets/11453507/15522472/f105815c-2212-11e6-8fe6-04f767842be8.JPG)

![onimusha 2 5](https://cloud.githubusercontent.com/assets/11453507/15522476/f764dd72-2212-11e6-8027-7782ace4370e.JPG)

![onimusha 2 6](https://cloud.githubusercontent.com/assets/11453507/15522477/fcb91f36-2212-11e6-8f9d-2472f69d8d58.JPG)

![onimusha 2 7](https://cloud.githubusercontent.com/assets/11453507/15522480/01f662f6-2213-11e6-9b10-318d6466bb59.JPG)

**Comment by boberto5888** [comment]
The issues shown above were resolved as of early 2017.
![0](https://user-images.githubusercontent.com/40678558/50462949-d4420280-0945-11e9-94fe-92a677cebb26.png)
  - The green tint was fixed by commit https://github.com/jpd002/Play-/commit/db71a10a7728f56ea924d20396ffa72f6b0f81d1, more details can be found on #448. 
  - Broken/missing geometry was fixed at some point between https://github.com/jpd002/Play-/compare/fc7152e2...016a4df4. 
    Maybe/probably these depth test changes https://github.com/jpd002/Play-/commit/91831baf91bef42c592c182995a792a212e8db57. 


----  

Unfortunately the game was then broken by commit https://github.com/jpd002/Play-/commit/ac5b76f244d057cb82c083708cc2e4249eb91a1a. 
It no longer reaches the cutscene shown above as it hangs after the first scene of the prologue.

jpd002/Play-Compatibility#718

**Comment by jpd002** [comment]
Nice! Thanks for the detailed info on the impacts of commits! Closing this now that it has a compatibility tracker issue.
