### ISSUE TITLE
Kingdom Hearts (SLUS_203.70) New game intro bug (PSMCT24 transfer)

### ISSUE THREAD

**Issue by fkaa** [jpd002/Play-#448]
The intro sequence for creating a new game in KH shows up pretty green:
![](http://i.imgur.com/o47HSTU.png)
expected:
![](http://i.imgur.com/qtuD49B.png)

I tracked it down to [`CGSHandler::TransferWriteHandlerPSMCT24`](https://github.com/jpd002/Play-/blob/master/Source/gs/GSHandler.cpp#L717), but the incoming data seems to be malformed (only green component set? assuming format for PSMCT24 transfer is [rgb, rgb, ...]), but not sure where data comes from:
![](http://i.imgur.com/f9OC7Ln.png)

**Comment by jpd002** [comment]
Interesting. I assumed the problem was coming from the lack of 16-bit output support in IPU's CSC, but that wouldn't make much sense if it's uploading a texture in PSMCT24 format. Also, some of the parts where the "Disney" logo appear to have some color. Could be a problem in the MPEG decoder.

I'm not going to look at that right away, so if you'd like to dig deeper, I'll be available to answer your questions.

**Comment by jpd002** [comment]
After some investigation, seems the culprit was the IDEC command implementation. The block sent to color space conversion after block decoding was not in the right format. Commit https://github.com/jpd002/Play-/commit/db71a10a7728f56ea924d20396ffa72f6b0f81d1 fixes this.

**Comment by jpd002** [comment]
This was fixed a long time ago. Closing.
