### ISSUE TITLE
[Android] Kingdom hearts 2 crash the emulator

### ISSUE THREAD

**Issue by Jordanesquivez** [jpd002/Play-#476]
I heard alot of people got ingame with 10-14 fps but just about  when the game is about to go ingame i see 'unfortunately play! As stopped' and my device is samsung galaxy tab 3.. this is the first game to crash the app so im wondering what's the problem

**Comment by Keyaku** [comment]
Hi @Jordanesquivez!

I don't know where you heard people getting in-game because I can't find that anywhere. The [Compatibility List](https://github.com/jpd002/Play-/wiki/Compatible-games) indicates in every version of Kingdom Hearts II that won't load past cutscenes, if even that.
If friends told you that, they're probably lying.

The current `master` build doesn't have this fixed either, I'm afraid.

> this is the first game to crash the app so im wondering what's the problem

Many games currently crash the app, so it's not unique to KH2.

**Comment by Jordanesquivez** [comment]
hey @keyaku I meant that kh2 was the first game I tested that caused the app to crash,otherwise from superman returns which I tried recently... also when will new build be available and what improvements has been made or what to expect (for android)

**Comment by TheGamerPro1** [comment]
No it's not a lie, nor was that compatability list updated. One of the updates had KH2 run in-game, if you are crashing then it's maybe just the device.

**Comment by Jordanesquivez** [comment]
it even crash on the latest build @TheGamerPro1 I would like u to test this game and tell me your results

**Comment by Keyaku** [comment]
@TheGamerPro1
Hi!

I'm very sorry for the confusion I caused. Since I don't own an Android, all the data I could rely on was from the compatibility list.

Since I made that comment, I've made some tests and the game does indeed run in-game on macOS for me (which made me update the list since it previously indicated it wouldn't get past cutscenes), but it won't even load the first cutscene on my iPhone (at least not yet).

If it runs on your Android, then would you kindly update the list with your results?

Thank you!

**Comment by jpd002** [comment]
The game crashes on 32-bit ARM devices, but it should work on 64-bit ARM devices. I'll fix the issue with 32-bit devices.

**Comment by Keyaku** [comment]
@jpd002 I'm testing with an iPhone 6 (unjailbroken), so it's probably not related.
I'll do a thorough debugging once I get the time!

**Comment by jpd002** [comment]
https://github.com/jpd002/Play--CodeGen/commit/a399dc005c3c0a09bd486b1f51591af5f185cea2 fixes the crash on Android/AArch32. 

I'll try on iOS to see why it crashes.

**Comment by Jordanesquivez** [comment]
@jpd002 thank you very much for this fix
