### ISSUE TITLE
What can I do?

### ISSUE THREAD

**Issue by s1n** [jpd002/Play-#513]
I'm thinking of diving into helping improve this emulator because it looks like it has serious potential.

What can I do to help? Do you have any contributor getting started guides (that aren't style guides)?

**Comment by iOS4all** [comment]
@s1n well thanks to join here and welcome.
Please wait for the creator of this amazing project for more details and guide.

**Comment by Thunder07** [comment]
@s1n @jpd002 might be able to tell you how you could help if you specified what kind of programming are you capable of.
you could work on the CodeGen to add missing instruction set or optimise code generation,
you could have a look at the UI for example, I've gotten Qt client on linux and the same one on OSX/windows but they seemed bugged on those build, so thats something.
or you can have at my latest CMake script and suggest how I could clean it up.
Jean wanted to unify sqlite query code between Android/iOS.

**Comment by s1n** [comment]
Initially it doesn't matter what needs work, but long term I want to add support for libretroarch, so I'm not interested in improving the Qt GUI. While that's something I want, I want a working PS2 emulator more.

I'm capable of whatever, I've done all sorts of development in my career, including 10 years of C++ development.

I'll take a look at the sqlite code first. Any guides on how to set up and do the edit/compile/run loop quickly?

**Comment by Thunder07** [comment]
unfortunately there isn't a straight forward guide yet, but I'm [currently](https://github.com/jpd002/Play-/issues/506) working standardising the entire build for all platform through cmake, so hopefully it will soon be as easy as, `cmake ..; cmake --build .`, you can jump the gun and use my repos but you'll need to backport any commits if you want to push a PR. (but since you want to look at the sqlite code, you should avoid my repos since I've a PoC branch for iOS which I'm not really happy with, no iPhone= no iPhone build knowledge and I'm working on the android branch, nearly done, 1 linking error, "-lrt" not sure where this is being added but it's breaking the build)

but to provide you with some basic steps.
clone all the branches,
```
git clone https://github.com/jpd002/Play-Build.git Play-Build
cd Play-Build
git submodule update --init --recursive
git submodule foreach git pull origin master
```

setup boost

edit `ExternalDependencies.mk ExternalDependencies.xcconfig ExternalDependenciesMySql.userprops` of the project you want to build.

try to build, you'd get few linking, missing headers errors, because of missing dependencies resolve those and you should have a working build.
if you're stuck at a particular step let me know and I'll try to help

**Comment by Deathlock47** [comment]
@s1n Issues within vector unit emulation are what currently stops a number of games (e.g. missing polygons and garbled textures in gta sa, nfs underground 2, etc.) from working properly and probably prevents some from working at all. I suggest that you work on fixing them

**Comment by s1n** [comment]
@Deathlock47 where would I find that code?

**Comment by Deathlock47** [comment]
@s1n Source/ee/ probably but I'm not entirely sure, you should ask @jpd002 about that

**Comment by jpd002** [comment]
@s1n Welcome and thanks for your interest in contributing to the project.

As @Thunder07 mentioned, there's work being done to make the project setup easier. On Windows, it should only be a matter of opening `Play/build_win32/Play.sln` to build the project after checking out the `Play-Build` repo and updating the submodules.

If you want to have an idea of the kind of changes needed to fix the kind of issues mentioned by @Deathlock47, you can take a look at the (clip_delay)[https://github.com/jpd002/Play-/tree/experimental/clip_delay] branch. Diagnosing those problems can take a long time and the frame debugger is a good way to get started on your investigation.

Also, many games won't boot because of missing stuff in the HLE kernel. Most of the time, it's a matter of looking at the emulator's log to see if there's anything fishy going on for a particular game that can't boot. If you need more info about something suspicious you see in a game, don't hesitate to post it here.
