### ISSUE TITLE
Screenshot feature

### ISSUE THREAD

**Issue by Thunder07** [jpd002/Play-#520]
Hi there,
I've been trying to capture the frame buffer and save it as a screen shot but I've ran into few issues.

my 1st attempt: if I try to call `ReadFramebuffer` from the UI e.g after editing `GSH_OpenGLMacOSX::ReadFramebuffer` to call it's super/inherited function, I've also had to edit `GSH_OpenGL::ReadFramebuffer`  `glReadPixels` `GL_BGR` to `GL_RGB`
```
	NSSize contentSize = [outputWindowController contentSize];
	auto m_w = static_cast<unsigned int>(contentSize.width);
	auto m_h = static_cast<unsigned int>(contentSize.height);
	auto m_buffer = Framework::CBitmap(m_w, m_h, 24);
	g_virtualMachine->m_ee->m_gs->ReadFramebuffer(m_w, m_h, m_buffer.GetPixels());

	Framework::CStdStream outputStream("/Users/__USER__/savehere.bmp", "wb");
	Framework::CBMP::WriteBitmap(m_buffer, outputStream);
```
in Odin for e.g The screenshot would be zoomed to to one corner (which meant my buffer was smaller than the frame buffer)
![savehere2](https://cloud.githubusercontent.com/assets/5013823/22380884/1ba82ee8-e4b7-11e6-997c-448c5cfda360.png)

my 2nd attempt was to edit `GSH_OpenGL::ReadFramebuffer` directly since I can access the frame buffer height/width from there to get the right size

```
	for(const auto& candidateFramebuffer : m_framebuffers)
	{
		
		auto m_buffer = Framework::CBitmap(candidateFramebuffer->m_width*m_fbScale, candidateFramebuffer->m_height*m_fbScale, 24);
		Framework::CStdStream outputStream("/Users/__USER__/savehere.bmp", "wb");
		Framework::CBMP::WriteBitmap(m_buffer, outputStream);
			break;
	}
```
with this, for e.g in KH I get a huge blank/black image with the full screenshot of the game in the top corner. I've noticed though in Odin I get the correct full screenshot image :/ (I'll post an example later as I overwrote the older images during later trials)

so how do I go about find the correct frame buffer size?

**Comment by jpd002** [comment]
Multiplying the framebuffer's size by `m_fbScale` sounds right. Also, framebuffers have a fixed height of 1024 to make up the fact that there's no way to specify a framebuffer's height on the PS2, so a large part of the framebuffer will be empty. 

The `CBitmap` probably needs to be 32-bpp as all framebuffers use a RGBA8 texture for their color attachment. 

Also, depending on how/when you call your function, you might get wrong results since the rendering thread is doing its work independently. Ideally, the screen shot should be generated after the back buffer has been flipped (using the `OnNewFrame` event).

I haven't thought much about building a proper screenshot or video capture feature, but, ideally, the screen capture would contain everything you would see on a TV screen, which would involve handling the CRTC parameters properly. The current GS handler design doesn't really help with that (`ReadFramebuffer` was supposed to do that job, but it's not really good at it).

Hope that helps, if you've got any other questions, don't hesitate to ask.

**Comment by Thunder07** [comment]
forgive the [commit](https://github.com/Thunder07/Play-/commit/cdb829b9d8ed0a539ff5abb95f21dd1f9c304026) I was also interested in `Nuanceur::CShaderBuilder` if that even useful on linux :p

with that commit I was able to get the 3 screenshot below
![ffxii](https://cloud.githubusercontent.com/assets/5013823/22438683/d39c1996-e724-11e6-8bcb-f2fed79d7e2c.jpg)
![ffxii-2](https://cloud.githubusercontent.com/assets/5013823/22438681/d37fa554-e724-11e6-8af6-43724138ac3f.jpg)
beside the picture being upside down, within the same game but at different phases it seems to be getting different results :/
![crash](https://cloud.githubusercontent.com/assets/5013823/22439867/25979aaa-e729-11e6-8e06-5356baf31208.jpg)

I'll try `OnNewFrame `, but I seem to be getting consistent results as is, the issue is trying to get the correct height and width at times as well. Ill scan for existing code that might help with that and see if i can come up with anything useful.

and I think the picture below was with fix height of 1024 (extra black border in the bottom)
![ffxii-1024](https://cloud.githubusercontent.com/assets/5013823/22438682/d39be8d6-e724-11e6-92a6-6edcd4e9a26a.jpg)

**Comment by Thunder07** [comment]
ok I got it to work correctly, using height, width, offset from the [switch statement](https://github.com/jpd002/Play-/blob/master/Source/gs/GSH_OpenGL/GSH_OpenGL.cpp#L184), looking at simplifying it if possible.

**Comment by Jordanesquivez** [comment]
Hey there sorry to interrupt, but is there any new builds available i almost thought it got discontinued

**Comment by jpd002** [comment]
Due to the recent changes with the build system (now using CMake), I wasn't able to produce new versions due to issues with my local build servers. Instead of fixing my build servers, I decided to invest time getting deployment to work with AppVeyor/Travis. The [work](https://github.com/jpd002/Play-/tree/deploy) is almost complete, I just need to get Android code signing to work.

**Comment by Thunder07** [comment]
with this merged, I'm closing this issue, Thanks.
