### ISSUE TITLE
Would a patreon help speeding things up?

### ISSUE THREAD

**Issue by yahfz** [jpd002/Play-#538]
Patreon has been a really nice incentive who has worked out in every single emulator out yet. CEMU just surpassed 20,000U$/month. What do you think about it?

**Comment by jpd002** [comment]
If it would allow me to quit my day job, I guess it could work, since my lack of time comes from there. But I doubt people would raise that much money. I would also feel uncomfortable receiving money for this work considering the dodgy legal aspect of emulators.

**Comment by Thunder07** [comment]
the question is, how much is "that much money"? I know you hold a high enough position in your line of work, and I've personally avoid suggesting this, as I know it's probably be tough to match that.

But I know the consensus about PCSX2 is very divided, some are really happy with it, some are not, you also already hold the advantage of running on OSX, iOS, Android (but for how long) so there is a potential for a successful Patreon campaign. for that though, the question is, what will you be able to promise the backers, a better, faster, more accurate, less glitchy emulator, (fulfil their gaming desires :p ) if so, I'd say, it's worth a shot. I believe you're only funded if you hit your goal anyway, so worst case scenario, you'd take a small hit to your bride for not achieving a certain level of support :p .


as for the legality aspect, and while I'm not a legal expert, as far as I'm concerned, RE and emulator have always been fair game from a legality point of view, but that hasn't stopped companies such as Nintendo, Sony from trying to sue the people involved before, they've failed, but tried (Sony failed but managed to stop 1 emu dev due to legal costs), but at this stage, I don't think Sony would be as concerned with `another` PS2 emulator as they would be with PS3 or perhaps a PS4.
