### ISSUE TITLE
Final Fantasy X Blue Screen in Underwater Ruins

### ISSUE THREAD

**Issue by Ripper69** [jpd002/Play-#632]
When you get to the underwater ruins after being picked up by the al bhed ship, the screen turns blue, blocking vision and making progress nearly impossible

**Comment by atomic83GitHub** [comment]
Can you post a screenshot of this issue?

**Comment by jpd002** [comment]
I reckon this is due to a division by 0 that the game does (which doesn't cause any issue on a real PS2, but generates a IEEE exception on CPUs that have a compliant implementation). That one's not easy to fix, but I've been doing some experimentation to make sure the emulator handle these cases correctly.

**Comment by ahumbledevoloper** [comment]
This could be the same issue with the black screen in Naruto Shippuden: ultimate ninja 5

**Comment by jpd002** [comment]
Probably not.

**Comment by Ripper69** [comment]
Here's a Screenshot
![ytjytd](https://user-images.githubusercontent.com/31782776/30244983-09d52e24-95c3-11e7-9349-cbd6b05349a6.png)

**Comment by jpd002** [comment]
Thanks for the screen shot. Yeah, this is the issue I was talking about. Happens in many places in the game and also in FFX-2. It can go away if you move away from the scene that causes problems (but yeah, it's a bit hard to find out where you're going).

**Comment by jpd002** [comment]
Should be fixed now.
