### ISSUE TITLE
[Feature request] Add the support for external GS plugins

### ISSUE THREAD

**Issue by atomic83GitHub** [jpd002/Play-#657]
The request here is to implement a function in Play! to be able to use an external GS plugin. This can be a  nice speed up for the emulator, allow to track core bugs more easly and essentialy add the possiblity to make a "custom implementation" of the GS for some specific games like the VPU.

Hope get you help

**Comment by atomic83GitHub** [comment]
Ok, I will reopen this later.

**Comment by jpd002** [comment]
The emulator's architecture already allows for different GS handlers to be used at compile time. I don't think there's much value in supporting a runtime plugin system, especially since the emulator is open source. Maybe there'll be an option to enable Vulkan at some point, but I don't see a plugin system coming anytime soon.
