### ISSUE TITLE
Frame rate too high in some games (ex.: Odin Sphere)

### ISSUE THREAD

**Issue by natuschaos** [jpd002/Play-#674]
Did a try with this game and it runs very nice with minor graphics bugs (some lines) but the speed is surpacing 60fps, many times it runs even at 87fps and the sound could be unsynchronized because of high fps. I think that option to lock at 30 or 60 fps should fix that. (sorry if I say somenthing that not makes sense I don't know nothing about ps2 hardware.
![way to fast](https://user-images.githubusercontent.com/23426146/38050181-8e283e76-32a0-11e8-8b9a-33bc553f2466.png)

(Update) The lines are not textures bugs is just a result of using options like the bilinear filter and high res.

**Comment by atomic83GitHub** [comment]
If you have an nivdia card, there should be a framelimiter enable by the driver itself.

**Comment by jpd002** [comment]
I've built a frame limiter, but it still needs testing on other platforms to see if it breaks anything.

If you can build the emulator yourself, here's the branch: https://github.com/jpd002/Play-/tree/frame_limit.
Otherwise, I'll post the link to the build once it's ready.

**Comment by natuschaos** [comment]
@atomic83GitHub I tryed that and I get no sound at'all. I will wait for @jpd002 build.

**Comment by literalmente-game** [comment]
@natuschaos Build compiled https://ci.appveyor.com/api/buildjobs/vhr9s314r3lnph9i/artifacts/d1e7bd4a%2FPlay-0.30-64.exe

**Comment by natuschaos** [comment]
Tested with the build, sound stop and came back at every second running at 32fps, sounds like is ploblem with audio emulation, Let's wait and see, I believe this will be fixed in further development.

**Comment by Thunder07** [comment]
sound stopping and returning is caused by the game no running at full speed, as far as I know audio is processed on a seperate thread, thus runs at full speed all the time, so the music finishes playing and is waiting for the game to catch up. there has been request to sync the audio the the framerate, but I'd rather have stop/restart then to listen to cat getting stung

**Comment by ramapcsx2** [comment]
Audio generation has to run in sync with the core, otherwise compatibility will be lowered as games miss their events.
So if you want skip free audio, you either need 100% speed or use time stretching (speed adjusted audio).

**Comment by jpd002** [comment]
@natuschaos : Does it run at 32fps all the time or just at some places in the game? If it's running at a constant 32fps, that means there's something broken in the frame limiter.

@Thunder07 : You're right about the fact that it's caused by the game not running at full speed, but sound generation is not handled in a separate thread. The emulator renders the SPU's output at every millisecond in the PS2's time. The buffer into which the SPU's output is rendered is 400ms long and is queued on the sound output device when it's filled.

**Comment by natuschaos** [comment]
Just like @Thunder07 said the sound follow the fps, and @jpd002 yes, the framerate change the all time but most of time it keep at 32 or 33fps on that build, with vsync on on Nvidia driver I get 60 on any normal build and the sound don't lag, looks like this game run at 60fps at ps2 hardware.

**Comment by jpd002** [comment]
Found out it's possible to enable VSync using a WGL call (7bcb74d8fc53de92f515c6801f94737c6aaaec8b). I'll leave the generic frame limiter out for now since it was potentially not working very well according to @natuschaos.
