### ISSUE TITLE
Android External Gamepad Support

### ISSUE THREAD

**Issue by devilgoldy** [jpd002/Play-#73]
Make play with external gamepad support

**Comment by jpd002** [comment]
On which platform? 

PC should already have support for gamepads.
I'm working on adding support for gamepads on Android.

**Comment by devilgoldy** [comment]
Android  and put the larft and right analogue sticks

**Comment by jpd002** [comment]
Analog sticks are now in the latest weekly build (2015-07-05). External gamepad support coming next.

**Comment by devilgoldy** [comment]
when play run game smoothly because current generation android phone have better CPU and GPU compare to ps2

**Comment by devilgoldy** [comment]
also all gamepads support on play including six axis controller

**Comment by devilgoldy** [comment]
ps2 gaming resolution also low compare to android games

**Comment by Evolution0** [comment]
@devilgoldy 

And current PCs have more power than both the PS2 and android devices, emulating a system requires magnitudes more than the original hardware so that argument doesn't hold up.

The resolution *would* be low, its rendering it in native after all and even mobile devices have a higher resolution these days than what PS2 games render in natively. (Keep in mind PS2 = Pre-HD era) Some late games supported  480p/1080i output though but they were few and had restrictions (Grand Turismo 4).

You would have to wait till Play! is at the point where enhancement options are viable.

**Comment by jpd002** [comment]
Added basic external gamepad support: a13a0fb98685eab2c590292deb41bc2aa6ff07ba. Will be in next weekly build. (2015-07-12)
