### ISSUE TITLE
Updating TheGamesDB API

### ISSUE THREAD

**Issue by Zer0xFF** [jpd002/Play-#736]
Just wanted to give you a heads up, as of today, I've switched off the legacy server for TGDB API, which means Play! cover fetcher would stop working.

but I've also started working on C++ implementation for `Play!`, I'm currently using https://github.com/nlohmann/json for son parser, since we don't have one for this project.

I know you've entertained the idea of removing cover editor, so I might get that out of the way as well.

**Comment by Zer0xFF** [comment]
yup, I plan on using that branch.


one think I noticed getting the code to work on android, I had to call the `*. PrepareClassInfo()` to set values, is that intentional or is there something messing?

```

JNIEXPORT jint JNI_OnLoad(JavaVM *vm, void *reserved)
{
    JNIEnv *env;
    if (vm->GetEnv(reinterpret_cast<void **>(&env), JNI_VERSION_1_6) != JNI_OK) {
        return -1;
    }

    Framework::CJavaVM::SetJavaVM(vm);
    java::net::URL_ClassInfo::GetInstance().PrepareClassInfo();
    java::net::HttpURLConnection_ClassInfo::GetInstance().PrepareClassInfo();
    java::io::OutputStream_ClassInfo::GetInstance().PrepareClassInfo();
    java::io::InputStream_ClassInfo::GetInstance().PrepareClassInfo();

    return JNI_VERSION_1_6;
}
```

**Comment by Zer0xFF** [comment]
Ok, got the new API working, and scan is also good.

Do you want to remove just the editor or the long click menu as well?

**Comment by jpd002** [comment]
Cool!

Yep, adding calls to `PrepareClassInfo` is necessary to make the Java interop work properly.

I'd like to keep the long click menu. The `Overview` field is missing from the bootable database though, it needs to be added and filled.

**Comment by jpd002** [comment]
Makes sense. We only used the games.db database to get a game's title by serial and then use that title to do a search on TGDB. If you can search by serial on TGDB, then, that database is not necessary anymore.

Only use case I can think of is having a way to obtain a game's title even though you're not connected to the internet. But since the games.db database is not complete anyway, it's not really useful. Maybe there would be more useful data sources for that (redump.org or the compatibility tracker?).

In any case, let's deprecate the games.db database.

**Comment by Zer0xFF** [comment]
redump.org would most likely have a more complete name database, I actually had a quick look at it few days ago.
I'm planning to see whats the licensing if any on their database is, then im going to push that to TGDB as well.
