### ISSUE TITLE
 is this compatible with Mac OS 10.4 tiger if it isn't do you think you could make it compatible in the next update???

### ISSUE THREAD

**Issue by snes666** [jpd002/Play-#748]
I've been looking to play final fantasy x and x-2 for quite a while and I have got an Intel iMac from 2007 running mac os 10.4 I don't have any way to upgrade currently...
@jpd002

**Comment by snes666** [comment]
@unknownbrackets

**Comment by unknownbrackets** [comment]
Hm, not sure why you summoned me here, but from a quick check it looks like it requires 10.7 right now.  10.4 is quite old, but if you want to try I'd suggest you try compiling it on the device.

-[Unknown]

**Comment by snes666** [comment]
How do i do that just asking beacuse im new  @unknownbrackets

**Comment by unknownbrackets** [comment]
https://stackoverflow.com/questions/1204824/where-can-i-download-xcode-for-mac-os-x-10-4

I have no idea if it'll compile on Xcode 2.5.

-[Unknown]

**Comment by jpd002** [comment]
There might be a way to make it work, but it'll probably involve many major changes to the UI stuff. I'm not even sure Qt supports that macOS version, so it might involve ripping that out and replacing it with the old macOS native UI.

I'm going to close the issue since I've got no plans on doing that, but I can answer your questions if you'd like to take the time to make this work on that macOS version.

**Comment by snes666** [comment]
is there a ps2 emulator that supports my os like older version of a
ps2 emulator...

**Comment by uyjulian** [comment]
You won't be running a PS2 emulator on a PowerPC Mac.
