### ISSUE TITLE
Scooby Doo! Night of 100 frights issue

### ISSUE THREAD

**Issue by DarkUmbreon87v3rm** [jpd002/Play-#765]
Not working... [Video of problem](https://streamable.com/3cpei)

**BTW IM ON _IOS_**

**Comment by jpd002** [comment]
Did you get the emulator from TweakBox? I know their version is a bit old and it doesn't work on not jailbroken devices.

**Comment by DarkUmbreon87v3rm** [comment]
Umm i sideloaded the emulator not downloaded fron tweakbox

**Comment by jpd002** [comment]
Ok, from what I can gather from your screen shot, it seems that you're using a build that doesn't have this commit: https://github.com/jpd002/Play-/commit/669fd2268654ee5aef5841f176e5f7c6e489cc01. 

If your build doesn't have this commit, you get an issue very similar to what you have on your video where the emulator will shutdown immediately after launching a game (because it can't map a memory page with execute bit).

You could try other games too to make sure it's not game related. The game itself shouldn't be the issue: https://github.com/jpd002/Play-Compatibility/issues/780.

**Comment by jpd002** [comment]
Closing this. Readme file now has instructions regarding running on iOS.
