### ISSUE TITLE
Odin Sphere Black screen

### ISSUE THREAD

**Issue by Alulabxxx** [jpd002/Play-#79]
I try to launch odion sphere on build 20150705 x64 but screen remain black. On S/F show some number

**Comment by jpd002** [comment]
![os_1](https://cloud.githubusercontent.com/assets/6760433/8792900/3c1815da-2f3c-11e5-8162-789187489324.jpg)
![os_2](https://cloud.githubusercontent.com/assets/6760433/8792901/3d4ae8f6-2f3c-11e5-9544-6f838453524b.jpg)

Seemed to be only a small timer problem. Game looks pretty much playable otherwise. I'll have the fixes ready for the next weekly build (2015-07-26).

**Comment by jpd002** [comment]
0b35fe2f8863b073d532bb6048ad627045c370aa fixes the issue.

**Comment by jpd002** [comment]
Available in latest weekly.

**Comment by Alulabxxx** [comment]
When you release this version if you need a test i can do it for you, i have a lot of PS2 games in my collection ;) I also do a test on android with Note 3 if u need
