### ISSUE TITLE
Is it possible to use system boost library?

### ISSUE THREAD

**Issue by guoyunhe** [jpd002/Play-#813]
I am trying to package it for openSUSE. The build system has no network connection so the download boost step will fail. Can Play! support system boost library if available?

**Comment by Zer0xFF** [comment]
How are you initializing/cloning the repo without a network connection?

No, not as it stands it doesn't, though you could download boost archive ahead of time, place it in the appropriate folder, and the setup should continue from there.

**Comment by guoyunhe** [comment]
Thanks for the information!

The build service allows me to do some `git pull` before building (only a couple of operations are allowed). Not sure if I can download boost archive as well.

**Comment by guoyunhe** [comment]
Yes, it works. I just bundled all git sub-modules and the tarball of boost. And then upload the source for offline building on the building farm. https://build.opensuse.org/package/show/home:guoyunhe:branches:Emulators/libretro-play

**Comment by Zer0xFF** [comment]
I don't know how the build system works, but if you're allowed to include tar file, can't you call git clone, and use the boost tar? So that you're always up to date?

In retrospect, there is a long term plan to remove boost, I've already replaced all the usages, par filesystem. @jpd002, maybe it worth while having the build using std filesystem on supported platform and boost on the others (aka apple)

**Comment by Zer0xFF** [comment]
@guoyunhe with the latest commit, you should be able to build `Play!` from source without any changes.

**Comment by jpd002** [comment]
boost is not used by this project anymore. Closing this.
