### ISSUE TITLE
The newest version doesnt start up anymore - with the new merge

### ISSUE THREAD

**Issue by dragon212c** [jpd002/Play-#830]
Running Play! in the terminal produces this error

Play: /tmp/.mount_Play!-qY7Wfc/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.26' not found (required by /usr/lib/libX11.so.6)
Play: /tmp/.mount_Play!-qY7Wfc/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libglib-2.0.so.0)
Play: /tmp/.mount_Play!-qY7Wfc/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libp11-kit.so.0)
Play: /tmp/.mount_Play!-qY7Wfc/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.26' not found (required by /usr/lib/libp11-kit.so.0)

This to me seems that play! isn't using the latest version 2.30-2

System OS: Manjaro KDE Arch

**Comment by jpd002** [comment]
@Zer0xFF does this ring a bell to you?

**Comment by Zer0xFF** [comment]
I'm look at this right now, it seems including libc is causing issue, specifically on newer OS that use  newer version :/

removing it, causes it to work on newer OS, but breaks older ones :/

RPCS3 managed to avoid this problem, without including `glibc` 🤔

**Comment by dragon212c** [comment]
(Im a total noob at this) Would including an up-to-date version cause issues?

**Comment by Zer0xFF** [comment]
it might fix it, until the next OS that requires an even newer version.

**Comment by Zer0xFF** [comment]
Ok, so I've spent the day, looking into this.

its caused by us including `libc`, which I initially included to get it to boot on trusty... funny enough, I was using Xenial image the whole time
I've gotten a trusty travis build up, but still cant `Play!` to boot, since Qt is using newer version of `libdbus`, and installing a newer version, leads to other dependency issues (from Qt side)

solution is simple, We dont officially support trusty, and remove `libc` from the image.
I've already test the image on both Ubuntu 16.04 and Manjaro and they're booting just fine.

**Comment by dragon212c** [comment]
@Zer0xFF fantastic work! good job 👍

**Comment by Zer0xFF** [comment]
@dragon212c can I just get a conformation that everything is working on your end?

**Comment by dragon212c** [comment]
@Zer0xFF Sure thing, It now starts up normally and I hope im not being annoying can you check my other issue its less specific which is why maybe @jpd002 hasn't taken a look at it

heres the url: https://github.com/jpd002/Play-/issues/826
I understand if its not high on the priority list
