### ISSUE TITLE
[Request][Android]Debug Logger

### ISSUE THREAD

**Issue by acocalypso** [jpd002/Play-#86]
Could you add a debug logger for android and write the error logs, warning etc to a logfile on internal/sdcard.

I think this would be very helpfull for fixing bugs.

**Comment by LoungeKatt** [comment]
Rather than polluting the filesystem, it would be much better to have the emulator write to the logcat and (if desired) provide an option to print those logs on demand.

Writing to a file during operation means adding an obscene delay to constantly check for the file, open the file, write to the file, close the file, etc. Not to mention not every user wanting every log and having to track them down to free up space.

**Comment by acocalypso** [comment]
Yes you are right. But the option to write the log information to logcat is a good idea to think about

**Comment by LinkofHyrule89** [comment]
I know some of the logs are automatically collected and sent to the developer via the Google Play Developer Console. He just added official Android TV support so those devices should be sending logs to him as well.

**Comment by acocalypso** [comment]
@jpd002 is it possible to add a dev option in the settings menu to activate log output to logcat?

**Comment by jpd002** [comment]
@acocalypso The current logging system is pretty heavy because almost everything is logging stuff (disabled in release builds). I don't really know what kind of information would be useful, except for GLES context creation stuff which seems to be the biggest Android related problem at the moment.
