### ISSUE TITLE
Add Dynamic Recompiler to improve speed emulation

### ISSUE THREAD

**Issue by zminhquanz** [jpd002/Play-#89]
add Dynarec ( JIT ) Recompiler to compile from ARM , x86 to target Core on Playstation 2 is EmotionEngine , IOP , 2 Vector Unit

**Comment by Fadi5555** [comment]
I think this is a good I for enhancing the speed for emu.

The ppsspp is already use it. And the results is fantastic.

Also if they could add (non-buffered)
This is to makes games looks super sharp and clear and full HD
Also fast mem will help for males ges speed up.

Also if they makes

**Comment by bigianb** [comment]
I don't understand what this issue is about. Play uses a recompiler - it does not have an interpreter. Of course even if it didn't the aim is to covert MIPS IV variant instructions to arm or x86, not the other way around as specified above. I'm also confused about what non-buffered or fast mem means in this context. Maybe they are implementation details of some other emu - in any case I don't think they are applicable or relevant here.

**Comment by adriandennis17** [comment]
@bigianb your right, the the implementation details are from "PPSSPP" @Fadi5555 just because it works for that emulator doesn't mean it will work for "Play!" .

**Comment by Fadi5555** [comment]
@adriandennis17 aha got your point 
Well I mean if anything like that could be help for making the games speed up as well as a feature for making games looks in full hd.

Anyway step by step the project will be more stable and fast as well.

**Comment by jpd002** [comment]
As @bigianb mentioned, Play! already uses a recompiler. 

I'm working on some speed hacks that will improve emulation speed on some 2D games and demos significantly (https://github.com/jpd002/Play-/tree/speedhack_test). As for 3D games, most of the time is spent executing VU code, which is quite heavy, but there is some optimizations that can be done there to improve speed.
