### ISSUE TITLE
Restident evil dead aim

### ISSUE THREAD

**Issue by paulaz2** [jpd002/Play-#93]
@jpd002 MisterHubs said that restident evil dead aim crashes the emulator what could be the problem?

**Comment by MisterHubs** [comment]
It crashes due to an unimplemented instruction(s), it seems, but I can't determine which since I just used an exception catcher, so someone more competent than me will have to get the game and test/analyze the issue, or wait until I can manage to find the exact instructions, but I still can't update the JIT anyways.

**Comment by paulaz2** [comment]
Thanks

**Comment by atomic83GitHub** [comment]
There is a compat report for that game, this should be close.

**Comment by jpd002** [comment]
Indeed: https://github.com/jpd002/Play-Compatibility/issues/376.
