### ISSUE TITLE
[Question] OpenGL on iOS devices

### ISSUE THREAD

**Issue by brand175** [jpd002/Play-#968]
Why does OpenGL run so good on Play! emulator on my iOS device. I can be able to play 007 Nightfire at 60fps on 1080p. When i'm using Dolphin Emulator on my iOS device with the OpenGL backend, it struggles to get 30fps. Is there any differences that OpenGLES 3.0 use on PS2 than Gamecube/Wii. Perhaps PS2 uses less OpenGL features?

**Comment by Dragon20C** [comment]
ps2 more powerful simple as that.

**Comment by literalmente-game** [comment]
Can you _please_ close this issue (as it's not an actual issue, just a question)? If you want to discuss PS2 emulation, ask in our Discord https://discord.gg/h6XUXD2

**Comment by tiagomouradjesus** [comment]
Playstation 2 has never been more powerful than the GameCube, because the PS2 is graphically weak the games are much lighter, GameCube has the most powerful graphics, which makes your phone weigh and catch the jog.

**Comment by tiagomouradjesus** [comment]
PS2 is much lighter than GameCube. GameCube games have more powerful graphics than Playstation 2, so your phone runs the PS2 game version much better than GameCube , and certainly the play 2 version has Menas lighting and details, the GC version has more lighting and details, that's why the game in the GameCube emulator weighs more😎✌️
