### ISSUE TITLE
Qt Debugger Issues

### ISSUE THREAD

**Issue by jpd002** [jpd002/Play-#997]
Opening this to document the issues I've seen using the new Qt debugger:

- [x] Frame Debugger: Draw kicks are not highlighted.
- [x] Frame Debugger: Navigating draw kicks (using prev/next buttons) doesn't change the selected item in the list to the current draw kick.
- [x] Frame Debugger: Draw call highlight doesn't work properly if resolution multiplier is greater than 1.
- [x] Debugger: If we close views (ex.: threads or functions) and reopen them again, the contents are not visible anymore.

Probably not going to address these ATM, so, if you want to take a look at it @Zer0xFF, lemme know. Also, I've been doing some tweaks in the `debugger_adjustments` branch, just tell me if you see something strange.

**Comment by Zer0xFF** [comment]
I'll take a look at them.

as for `debugger_` I'm keep track, to see what i missed 😬 so ill let you know if i note anything.

Though something you might be interested in https://doc.qt.io/qt-5/qheaderview.html#defaultSectionSize-prop aka  `verticalHeader()->setDefaultSectionSize(SIZE)` if you want to set cell vertical height for the dism, just be sure to call it before `setModel()` https://github.com/jpd002/Play-/blob/master/Source/ui_qt/DebugSupport/DisAsmWnd.cpp#L51 otherwise it would end up setting the height for every row one by one (so its best to set it before we have any cells)

**Comment by jpd002** [comment]
Found a small issue in the frame debugger with the multiplier handling:

![image](https://user-images.githubusercontent.com/6760433/104231919-9bd2cb80-541d-11eb-83b6-907173a5bcd5.png)

The draw call highlight position's is not transformed properly.

Also, seems the problem of closing and reopening views doesn't work for the threads list (it seems to work for other views though).

**Comment by Zer0xFF** [comment]
grrrr.... looking at it now, should be simple fix.

I noticed that modes are broken as well, so i'd scale those to fix that, ofc doing so they'd no longer be 448P and 448I but they would still keep that aspect ratio.

**Comment by jpd002** [comment]
Alright, closing this as issues are now fixed.

I backed out of the font size change in my branch because while it was giving a nice result on macOS, it doesn't look great on Windows. I'm thinking it might be nice to have some way to configure the font used in the debugger views, but then, it's probably gonna break other things.

**Comment by Zer0xFF** [comment]
> it's probably gonna break other things.

each widget can have its own font setting, so it shouldnt be a problem no?

**Comment by jpd002** [comment]
> each widget can have its own font setting, so it shouldnt be a problem no?
I was thinking that maybe the cells in the table views might now adapt well to arbitrary font sizes. For example on macOS, with the current font size, the memory view shows ellipsis (...) instead of values in memory. I added 1 px to the font size and it fixed it, but yeah, I'm not sure adding constants everywhere is great.

**Comment by Zer0xFF** [comment]
Im actually looking at this now, the problem with the ellipsis, we can probably be attributed that to using fixed cell size, thus needing to calculate the size of the cell manually, which can be very error prone, since cell width doesnt equal just character width, but also any padding, which we dont take into account(and if we did, the maths is likely to get even more complicated).

I am however, testing a solution on windows now, basically setting the cells to resize to content, which fixes that problem, allowing us to completely remove ``ResizeColumns()` logic, going a step further, we can then request column width from the table (instead of attempting to calculate it) for the auto column logic.
